from unittest import TestCase

from post_selector.post_checker import PostChecker
from post_selector.query_parser import QueryParser


class TestQueryParser(TestCase):

    def setUp(self) -> None:
        self.parser = QueryParser()

    def test_query_to_dict(self):
        doc = """("#withgalaxy"  OR "#withgalaxy*" OR "?#withgalaxy"
 OR "*1億800萬像素*" OR "*1億800萬像素*"
 OR "*108 เมกะพิกเซล*" OR "*108เมกะพิกเซล*"
 OR "108 megapíxeles*" OR "?108 megapíxeles" OR "108megapíxeles" OR "?108megapíxeles" OR "108megapíxeles?" OR "#108megapíxeles"
 OR "108 megapíxel*" OR "?108 megapíxel" OR "108megapíxel" OR "?108megapíxel" OR "108megapíxel?" OR "#108megapíxel"
 OR "?108 МП" OR "108 МП?" OR "108МП" OR "108МП?" OR "?108МП" OR "#108МП"
 OR "108-мегапиксельная*" OR "?108-мегапиксельная" OR "108-мегапиксельная" OR "?108-мегапиксельная" OR "108-мегапиксельная?" OR "#108-мегапиксельная"
 OR "108 мегапиксельная*" OR "?108 мегапиксельная" OR "108мегапиксельная" OR "?108мегапиксельная" OR "108мегапиксельная?" OR "#108мегапиксельная"
 OR "108-мегапиксельные*" OR "?108-мегапиксельные" OR "108-мегапиксельные" OR "?108-мегапиксельные" OR "108-мегапиксельные?" OR "#108-мегапиксельные"
 OR "108 мегапиксельные*" OR "?108 мегапиксельные" OR "108мегапиксельные" OR "?108мегапиксельные" OR "108мегапиксельные?" OR "#108мегапиксельные"
 OR "1억 800만 화소*" OR "?1억 800만 화소" OR "1억800만화소" OR "?1억800만화소" OR "1억800만화소?" OR "#1억800만화소"
 OR "1억800만 화소*" OR "?1억800만 화소" OR "1억800만화소" OR "?1억800만화소" OR "1억800만화소?" OR "#1억800만화소"
 OR "*108メガピクセル*" OR "*108メガピクセル*"
 OR "108 mégapixel*" OR "?108 mégapixel" OR "108mégapixel" OR "?108mégapixel" OR "108mégapixel?" OR "#108mégapixel"
 OR "108 megapixel*" OR "?108 megapixel" OR "108megapixel" OR "?108megapixel" OR "108megapixel?" OR "#108megapixel"
 OR "?108 MP" OR "108 MP?" OR "108 MP" OR "108MP" OR "108MP?" OR "?108MP" OR "#108MP" OR "?108MP?"
 OR "*1.08亿像素*" OR "*1.08亿像素*"
 OR "*千萬像素*" OR "*千萬像素*"
 OR "천만 화소*" OR "?천만 화소" OR "천만화소" OR "?천만화소" OR "천만화소?" OR "#천만화소"
 OR "*1???萬像素*" OR "*1???萬像素*"
 OR "*1千?00萬像素*" OR "*1千?00萬像素*"
 OR "*1? เมกะพิกเซล*" OR "*1?เมกะพิกเซล*"
 OR "1? Megapíxel*" OR "?1? Megapíxel" OR "1?Megapíxel" OR "?1?Megapíxel" OR "1?Megapíxel?" OR "#1?Megapíxel"
 OR "1? Megapíxeles*" OR "?1? Megapíxeles" OR "1?Megapíxeles" OR "?1?Megapíxeles" OR "1?Megapíxeles?" OR "#1?Megapíxeles"
 OR "?1? МП" OR "1? МП?" OR "1?МП" OR "1?МП?" OR "?1?МП" OR "#1?МП"
 OR "1?-мегапиксельная*" OR "?1?-мегапиксельная" OR "1?-мегапиксельная" OR "?1?-мегапиксельная" OR "1?-мегапиксельная?" OR "#1?-мегапиксельная"
 OR "1? мегапиксельная*" OR "?1? мегапиксельная" OR "1?мегапиксельная" OR "?1?мегапиксельная" OR "1?мегапиксельная?" OR "#1?мегапиксельная"
 OR "1?-мегапиксельные*" OR "?1?-мегапиксельные" OR "1?-мегапиксельные" OR "?1?-мегапиксельные" OR "1?-мегапиксельные?" OR "#1?-мегапиксельные"
 OR "1? мегапиксельные*" OR "?1? мегапиксельные" OR "1?мегапиксельные" OR "?1?мегапиксельные" OR "1?мегапиксельные?" OR "#1?мегапиксельные"
 OR "1?00만 화소*" OR "?1?00만 화소" OR "1?00만화소" OR "?1?00만화소" OR "1?00만화소?" OR "#1?00만화소"
 OR "천?백만 화소*" OR "?천?백만 화소" OR "천?백만화소" OR "?천?백만화소" OR "천?백만화소?" OR "#천?백만화소"
 OR "*1?メガピクセル*" OR "*1?メガピクセル*"
 OR "1? Mégapixel*" OR "?1? Mégapixel" OR "1?Mégapixel" OR "?1?Mégapixel" OR "1?Mégapixel?" OR "#1?Mégapixel"
 OR "?1? MP" OR "1? MP?" OR "1?MP" OR "1?MP?" OR "?1?MP" OR "#1?MP"
 OR "*3???萬像素*" OR "*3???萬像素*"
 OR "*3千?00萬像素*" OR "*3千?00萬像素*"
 OR "*3? เมกะพิกเซล*" OR "*3?เมกะพิกเซล*"
 OR "3? Megapíxel*" OR "?3? Megapíxel" OR "3?Megapíxel" OR "?3?Megapíxel" OR "3?Megapíxel?" OR "#3?Megapíxel"
 OR "3? Megapíxeles*" OR "?3? Megapíxeles" OR "3?Megapíxeles" OR "?3?Megapíxeles" OR "3?Megapíxeles?" OR "#3?Megapíxeles"
 OR "?3? МП" OR "3? МП?" OR "3?МП" OR "3?МП?" OR "?3?МП" OR "#3?МП"
 OR "3?-мегапиксельная*" OR "?3?-мегапиксельная" OR "3?-мегапиксельная" OR "?3?-мегапиксельная" OR "3?-мегапиксельная?" OR "#3?-мегапиксельная"
 OR "3?мегапиксельная*" OR "?3?мегапиксельная" OR "3?мегапиксельная" OR "?3?мегапиксельная" OR "3?мегапиксельная?" OR "#3?мегапиксельная"
 OR "3?-мегапиксельные*" OR "?3?-мегапиксельные" OR "3?-мегапиксельные" OR "?3?-мегапиксельные" OR "3?-мегапиксельные?" OR "#3?-мегапиксельные"
 OR "3?мегапиксельные*" OR "?3?мегапиксельные" OR "3?мегапиксельные" OR "?3?мегапиксельные" OR "3?мегапиксельные?" OR "#3?мегапиксельные"
 OR "3???만 화소*" OR "?3???만 화소" OR "3???만화소" OR "?3???만화소" OR "3???만화소?" OR "#3???만화소"
 OR "*3?メガピクセル*" OR "*3?メガピクセル*"
 OR "3? Mégapixel*" OR "?3? Mégapixel" OR "3?Mégapixel" OR "?3?Mégapixel" OR "3?Mégapixel?" OR "#3?Mégapixel"
 OR "?3? MP" OR "3? MP?" OR "3?MP" OR "3?MP?" OR "?3?MP" OR "#3?MP"
 OR "*4???萬像素*" OR "*4???萬像素*"
 OR "*4千萬像素*" OR "*4千萬像素*"
 OR "*4? เมกะพิกเซล*" OR "*4?เมกะพิกเซล*"
 OR "4? Megapíxel*" OR "?4? Megapíxel" OR "4?Megapíxel" OR "?4?Megapíxel" OR "4?Megapíxel?" OR "#4?Megapíxel"
 OR "4? megapíxeles*" OR "?4? megapíxeles" OR "4?megapíxeles" OR "?4?megapíxeles" OR "4?megapíxeles?" OR "#4?megapíxeles"
 OR "?4? МП" OR "4? МП?" OR "4?МП" OR "4?МП?" OR "?4?МП" OR "#4?МП"
 OR "4?-мегапиксельная*" OR "?4?-мегапиксельная" OR "4?-мегапиксельная" OR "?4?-мегапиксельная" OR "4?-мегапиксельная?" OR "#4?-мегапиксельная"
 OR "4? мегапиксельная*" OR "?4? мегапиксельная" OR "4?мегапиксельная" OR "?4?мегапиксельная" OR "4?мегапиксельная?" OR "#4?мегапиксельная"
 OR "4?-мегапиксельные*" OR "?4?-мегапиксельные" OR "4?-мегапиксельные" OR "?4?-мегапиксельные" OR "4?-мегапиксельные?" OR "#4?-мегапиксельные"
 OR "4? мегапиксельные*" OR "?4? мегапиксельные" OR "4?мегапиксельные" OR "?4?мегапиксельные" OR "4?мегапиксельные?" OR "#4?мегапиксельные"
 OR "4???만 화소*" OR "?4???만 화소" OR "4???만화소" OR "?4???만화소" OR "4???만화소?" OR "#4???만화소"
 OR "4천만 화소*" OR "?4천만 화소" OR "4천만화소" OR "?4천만화소" OR "4천만화소?" OR "#4천만화소"
 OR "*4?メガピクセル*" OR "*4?メガピクセル*"
 OR "4? Mégapixel*" OR "?4? Mégapixel" OR "4?Mégapixel" OR "?4?Mégapixel" OR "4?Mégapixel?" OR "#4?Mégapixel"
 OR "?4? MP" OR "4? MP?" OR "4?MP" OR "4?MP?" OR "?4?MP" OR "#4?MP"
OR "?64 MP?"
 OR "*6400萬像素*" OR "*6400萬像素*"
 OR "*6千400萬像素*" OR "*6千400萬像素*"
 OR "*64 เมกะพิกเซล*" OR "*64เมกะพิกเซล*"
 OR "64 megapíxel*" OR "?64 megapíxel" OR "64megapíxel" OR "?64megapíxel" OR "64megapíxel?" OR "#64megapíxel"
 OR "64 megapíxeles*" OR "?64 megapíxeles" OR "64megapíxeles" OR "?64megapíxeles" OR "64megapíxeles?" OR "#64megapíxeles"
 OR "?64 МП" OR "64 МП?" OR "64МП" OR "64МП?" OR "?64МП" OR "#64МП"
 OR "64-мегапиксельная*" OR "?64-мегапиксельная" OR "64-мегапиксельная" OR "?64-мегапиксельная" OR "64-мегапиксельная?" OR "#64-мегапиксельная"
 OR "64 мегапиксельная*" OR "?64 мегапиксельная" OR "64мегапиксельная" OR "?64мегапиксельная" OR "64мегапиксельная?" OR "#64мегапиксельная"
 OR "64-мегапиксельные*" OR "?64-мегапиксельные" OR "64-мегапиксельные" OR "?64-мегапиксельные" OR "64-мегапиксельные?" OR "#64-мегапиксельные"
 OR "64 мегапиксельные*" OR "?64 мегапиксельные" OR "64мегапиксельные" OR "?64мегапиксельные" OR "64мегапиксельные?" OR "#64мегапиксельные"
 OR "6400만 화소*" OR "?6400만 화소" OR "6400만화소" OR "?6400만화소" OR "6400만화소?" OR "#6400만화소"
 OR "6천4백만 화소*" OR "?6천4백만 화소" OR "6천4백만화소" OR "?6천4백만화소" OR "6천4백만화소?" OR "#6천4백만화소"
 OR "*64メガピクセル*" OR "*64メガピクセル*"
 OR "64 mégapixel*" OR "?64 mégapixel" OR "64mégapixel" OR "?64mégapixel" OR "64mégapixel?" OR "#64mégapixel"
 OR "?64 MP" OR "64 MP?" OR "64MP" OR "64MP?" OR "?64MP" OR "#64MP"
 OR "*500萬像素*" OR "*500萬像素*"
 OR "*5百萬像素*" OR "*5百萬像素*"
 OR "*5 เมกะพิกเซล*" OR "*5เมกะพิกเซล*"
 OR "5 megapíxel*" OR "?5 megapíxel" OR "5megapíxel" OR "?5megapíxel" OR "5megapíxel?" OR "#5megapíxel"
 OR "5 megapíxeles*" OR "?5 megapíxeles" OR "5megapíxeles" OR "?5megapíxeles" OR "5megapíxeles?" OR "#5megapíxeles"
 OR "?5 МП" OR "5 МП?" OR "5МП" OR "5МП?" OR "?5МП" OR "#5МП"
 OR "5-мегапиксельная*" OR "?5-мегапиксельная" OR "5-мегапиксельная" OR "?5-мегапиксельная" OR "5-мегапиксельная?" OR "#5-мегапиксельная"
 OR "5 мегапиксельная*" OR "?5 мегапиксельная" OR "5мегапиксельная" OR "?5мегапиксельная" OR "5мегапиксельная?" OR "#5мегапиксельная"
 OR "5-мегапиксельные*" OR "?5-мегапиксельные" OR "5-мегапиксельные" OR "?5-мегапиксельные" OR "5-мегапиксельные?" OR "#5-мегапиксельные"
 OR "5 мегапиксельные*" OR "?5 мегапиксельные" OR "5мегапиксельные" OR "?5мегапиксельные" OR "5мегапиксельные?" OR "#5мегапиксельные"
 OR "500만 화소*" OR "?500만 화소" OR "500만화소" OR "?500만화소" OR "500만화소?" OR "#500만화소"
 OR "5백만 화소*" OR "?5백만 화소" OR "5백만화소" OR "?5백만화소" OR "5백만화소?" OR "#5백만화소"
 OR "*5メガピクセル*" OR "*5メガピクセル*"
 OR "5 mégapixel*" OR "?5 mégapixel" OR "5mégapixel" OR "?5mégapixel" OR "5mégapixel?" OR "#5mégapixel"
 OR "?5 MP" OR "5 MP?" OR "5MP" OR "5MP?" OR "?5MP" OR "#5MP"
 OR "*800萬像素*" OR "*800萬像素*"
 OR "*8百萬像素*" OR "*8百萬像素*"
 OR "*8 เมกะพิกเซล*" OR "*8เมกะพิกเซล*"
 OR "8 megapíxel*" OR "?8 megapíxel" OR "8megapíxel" OR "?8megapíxel" OR "8megapíxel?" OR "#8megapíxel"
 OR "8 megapíxeles*" OR "?8 megapíxeles" OR "8megapíxeles" OR "?8megapíxeles" OR "8megapíxeles?" OR "#8megapíxeles"
 OR "?8 МП" OR "8 МП?" OR "8МП" OR "8МП?" OR "?8МП" OR "#8МП"
 OR "8-мегапиксельная*" OR "?8-мегапиксельная" OR "8-мегапиксельная" OR "?8-мегапиксельная" OR "8-мегапиксельная?" OR "#8-мегапиксельная"
 OR "8 мегапиксельная*" OR "?8 мегапиксельная" OR "8мегапиксельная" OR "?8мегапиксельная" OR "8мегапиксельная?" OR "#8мегапиксельная"
 OR "8-мегапиксельные*" OR "?8-мегапиксельные" OR "8-мегапиксельные" OR "?8-мегапиксельные" OR "8-мегапиксельные?" OR "#8-мегапиксельные"
 OR "8 мегапиксельные*" OR "?8 мегапиксельные" OR "8мегапиксельные" OR "?8мегапиксельные" OR "8мегапиксельные?" OR "#8мегапиксельные"
 OR "800만 화소*" OR "?800만 화소" OR "800만화소" OR "?800만화소" OR "800만화소?" OR "#800만화소"
 OR "8백만 화소*" OR "?8백만 화소" OR "8백만화소" OR "?8백만화소" OR "8백만화소?" OR "#8백만화소"
 OR "*8メガピクセル*" OR "*8メガピクセル*"
 OR "8 mégapixel*" OR "?8 mégapixel" OR "8mégapixel" OR "?8mégapixel" OR "8mégapixel?" OR "#8mégapixel"
 OR "?8 MP" OR "8 MP?" OR "8MP" OR "8MP?" OR "?8MP" OR "#8MP"
 OR "*200萬像素*" OR "*200萬像素*"
 OR "*2百萬像素*" OR "*2百萬像素*"
 OR "*2 เมกะพิกเซล*" OR "*2เมกะพิกเซล*"
 OR "2 megapíxeles*" OR "?2 megapíxeles" OR "2megapíxeles" OR "?2megapíxeles" OR "2megapíxeles?" OR "#2megapíxeles"
 OR "2 megapíxel*" OR "?2 megapíxel" OR "2megapíxel" OR "?2megapíxel" OR "2megapíxel?" OR "#2megapíxel"
 OR "?2 МП" OR "2 МП?" OR "2МП" OR "2МП?" OR "?2МП" OR "#2МП"
 OR "2-мегапиксельная*" OR "?2-мегапиксельная" OR "2-мегапиксельная" OR "?2-мегапиксельная" OR "2-мегапиксельная?" OR "#2-мегапиксельная"
 OR "2 мегапиксельная*" OR "?2 мегапиксельная" OR "2мегапиксельная" OR "?2мегапиксельная" OR "2мегапиксельная?" OR "#2мегапиксельная"
 OR "2-мегапиксельные*" OR "?2-мегапиксельные" OR "2-мегапиксельные" OR "?2-мегапиксельные" OR "2-мегапиксельные?" OR "#2-мегапиксельные"
 OR "2 мегапиксельные*" OR "?2 мегапиксельные" OR "2мегапиксельные" OR "?2мегапиксельные" OR "2мегапиксельные?" OR "#2мегапиксельные"
 OR "200만 화소*" OR "?200만 화소" OR "200만화소" OR "?200만화소" OR "200만화소?" OR "#200만화소"
 OR "2백만 화소*" OR "?2백만 화소" OR "2백만화소" OR "?2백만화소" OR "2백만화소?" OR "#2백만화소"
 OR "*2メガピクセル*" OR "*2メガピクセル*"
 OR "2 mégapixel*" OR "?2 mégapixel" OR "2mégapixel" OR "?2mégapixel" OR "2mégapixel?" OR "#2mégapixel"
 OR "?2 MP" OR "2 MP?" OR "2MP" OR "2MP?" OR "?2MP" OR "#2MP"
 OR "*4K影片*" OR "*4K影片*"
 OR "*วิดีโอ 4K*" OR "*วิดีโอ4K*"
 OR "4K video*" OR "?4K video" OR "4Kvideo" OR "?4Kvideo" OR "4Kvideo?" OR "#4Kvideo"
 OR "video de 4K*" OR "?video de 4K" OR "videode4K" OR "?videode4K" OR "videode4K?" OR "#videode4K"
 OR "video 4K*" OR "?video 4K" OR "video4K" OR "?video4K" OR "video4K?" OR "#video4K"
 OR "4K Видео*" OR "?4K Видео" OR "4KВидео" OR "?4KВидео" OR "4KВидео?" OR "#4KВидео"
 OR "Відео 4К*" OR "?Відео 4К" OR "Відео4К" OR "?Відео4К" OR "Відео4К?" OR "#Відео4К"
 OR "VÍDEO 4K*" OR "?VÍDEO 4K" OR "VÍDEO4K" OR "?VÍDEO4K" OR "VÍDEO4K?" OR "#VÍDEO4K"
 OR "4K 동영상*" OR "?4K 동영상" OR "4K동영상" OR "?4K동영상" OR "4K동영상?" OR "#4K동영상"
 OR "4K 비디오*" OR "?4K 비디오" OR "4K비디오" OR "?4K비디오" OR "4K비디오?" OR "#4K비디오"
 OR "4K 영상*" OR "?4K 영상" OR "4K영상" OR "?4K영상" OR "4K영상?" OR "#4K영상"
 OR "*4Kビデオ*" OR "*4Kビデオ*"
 OR "VIDEO IN 4K*" OR "?VIDEO IN 4K" OR "VIDEOIN4K" OR "?VIDEOIN4K" OR "VIDEOIN4K?" OR "#VIDEOIN4K"
 OR "vidéo 4K*" OR "?vidéo 4K" OR "vidéo4K" OR "?vidéo4K" OR "vidéo4K?" OR "#vidéo4K"
 OR "*4K视频*" OR "*4K视频*"
 OR "فيديو بدقة 4K*" OR "?فيديو بدقة 4K" OR "فيديوبدقة4K" OR "?فيديوبدقة4K" OR "فيديوبدقة4K?" OR "#فيديوبدقة4K"
 OR "*8K影片*" OR "*8K影片*"
 OR "*วิดีโอ 8K*" OR "*วิดีโอ8K*"
 OR "8K video*" OR "?8K video" OR "8Kvideo" OR "?8Kvideo" OR "8Kvideo?" OR "#8Kvideo"
 OR "video de 8K*" OR "?video de 8K" OR "videode8K" OR "?videode8K" OR "videode8K?" OR "#videode8K"
 OR "video 8K*" OR "?video 8K" OR "video8K" OR "?video8K" OR "video8K?" OR "#video8K"
 OR "8K Видео*" OR "?8K Видео" OR "8KВидео" OR "?8KВидео" OR "8KВидео?" OR "#8KВидео"
 OR "Відео 8К*" OR "?Відео 8К" OR "Відео8К" OR "?Відео8К" OR "Відео8К?" OR "#Відео8К"
 OR "VÍDEO 8K*" OR "?VÍDEO 8K" OR "VÍDEO8K" OR "?VÍDEO8K" OR "VÍDEO8K?" OR "#VÍDEO8K"
 OR "8K 동영상*" OR "?8K 동영상" OR "8K동영상" OR "?8K동영상" OR "8K동영상?" OR "#8K동영상"
 OR "8K 비디오*" OR "?8K 비디오" OR "8K비디오" OR "?8K비디오" OR "8K비디오?" OR "#8K비디오"
 OR "8K 영상*" OR "?8K 영상" OR "8K영상" OR "?8K영상" OR "8K영상?" OR "#8K영상"
 OR "*8Kビデオ*" OR "*8Kビデオ*"
 OR "VIDEO IN 8K*" OR "?VIDEO IN 8K" OR "VIDEOIN8K" OR "?VIDEOIN8K" OR "VIDEOIN8K?" OR "#VIDEOIN8K"
 OR "vidéo 8K*" OR "?vidéo 8K" OR "vidéo8K" OR "?vidéo8K" OR "vidéo8K?" OR "#vidéo8K"
 OR "*8K视频*" OR "*8K视频*"
 OR "فيديو بدقة 8K*" OR "?فيديو بدقة 8K" OR "فيديوبدقة8K" OR "?فيديوبدقة8K" OR "فيديوبدقة8K?" OR "#فيديوبدقة8K"
 OR "Chụp nhanh video 8K*" OR "?Chụp nhanh video 8K" OR "Chụpnhanhvideo8K" OR "?Chụpnhanhvideo8K" OR "Chụpnhanhvideo8K?" OR "#Chụpnhanhvideo8K"
 OR "8K Videodan Fotoğraf*" OR "?8K Videodan Fotoğraf" OR "8KVideodanFotoğraf" OR "?8KVideodanFotoğraf" OR "8KVideodanFotoğraf?" OR "#8KVideodanFotoğraf"
 OR "*8K影片快拍*" OR "*8K影片快拍*"
 OR "*8K攝錄高清截圖*" OR "*8K攝錄高清截圖*"
 OR "VÍDEO EN 8K A FOTOGRAFÍA*" OR "?VÍDEO EN 8K A FOTOGRAFÍA" OR "VÍDEOEN8KAFOTOGRAFÍA" OR "?VÍDEOEN8KAFOTOGRAFÍA" OR "VÍDEOEN8KAFOTOGRAFÍA?" OR "#VÍDEOEN8KAFOTOGRAFÍA"
 OR "Фото из видео 8к*" OR "?Фото из видео 8к" OR "Фотоизвидео8к" OR "?Фотоизвидео8к" OR "Фотоизвидео8к?" OR "#Фотоизвидео8к"
 OR "Фотокадри з відео 8К*" OR "?Фотокадри з відео 8К" OR "Фотокадризвідео8К" OR "?Фотокадризвідео8К" OR "Фотокадризвідео8К?" OR "#Фотокадризвідео8К"
 OR "FOTOGRAFIA COM VÍDEO 8K*" OR "?FOTOGRAFIA COM VÍDEO 8K" OR "FOTOGRAFIACOMVÍDEO8K" OR "?FOTOGRAFIACOMVÍDEO8K" OR "FOTOGRAFIACOMVÍDEO8K?" OR "#FOTOGRAFIACOMVÍDEO8K"
 OR "8K 동영상 캡쳐*" OR "?8K 동영상 캡쳐" OR "8K동영상캡쳐" OR "?8K동영상캡쳐" OR "8K동영상캡쳐?" OR "#8K동영상캡쳐"
 OR "8K 동영상 스냅*" OR "?8K 동영상 스냅" OR "8K동영상스냅" OR "?8K동영상스냅" OR "8K동영상스냅?" OR "#8K동영상스냅"
 OR "8K 비디오 캡쳐*" OR "?8K 비디오 캡쳐" OR "8K비디오캡쳐" OR "?8K비디오캡쳐" OR "8K비디오캡쳐?" OR "#8K비디오캡쳐"
 OR "8K 비디오 스냅*" OR "?8K 비디오 스냅" OR "8K비디오스냅" OR "?8K비디오스냅" OR "8K비디오스냅?" OR "#8K비디오스냅"
 OR "*8Kビデオスナップ*" OR "*8Kビデオスナップ*"
 OR "Fermo Immagine 8K*" OR "?Fermo Immagine 8K" OR "FermoImmagine8K" OR "?FermoImmagine8K" OR "FermoImmagine8K?" OR "#FermoImmagine8K"
 OR "VIDÉO 8K SNAP*" OR "?VIDÉO 8K SNAP" OR "VIDÉO8KSNAP" OR "?VIDÉO8KSNAP" OR "VIDÉO8KSNAP?" OR "#VIDÉO8KSNAP"
 OR "8K Video Snap*" OR "?8K Video Snap" OR "8KVideoSnap" OR "?8KVideoSnap" OR "8KVideoSnap?" OR "#8KVideoSnap"
 OR "*8K视频快照*" OR "*8K视频快照*"
 OR "تصوير فيديو بدقة 8K*" OR "?تصوير فيديو بدقة 8K" OR "تصويرفيديوبدقة8K" OR "?تصويرفيديوبدقة8K" OR "تصويرفيديوبدقة8K?" OR "#تصويرفيديوبدقة8K"
 OR "?Khẩu độ" OR "Khẩu độ?" OR "Khẩuđộ"
 OR "?Diyafram" OR "Diyafram?" OR "Diyafram"
 OR "?光圈" OR "光圈?" OR "光圈"
 OR "?รูรับแสง" OR "รูรับแสง?" OR "รูรับแสง"
 OR "?abertura" OR "abertura?" OR "abertura"
 OR "?Диафрагма" OR "Диафрагма?" OR "Диафрагма"
 OR "?Bukaan" OR "Bukaan?" OR "Bukaan"
 OR "?조리개" OR "조리개?" OR "조리개"
 OR "?絞り" OR "絞り?" OR "絞り"
 OR "?Apertura" OR "Apertura?" OR "Apertura"
 OR "?Blende" OR "Blende?" OR "Blende"
 OR "?ouverture" OR "ouverture?" OR "ouverture"
 OR "?Aperture" OR "Aperture?" OR "Aperture"
 OR "?-Aperture" OR "-Aperture?" OR "-Aperture"
 OR "?Apertuur" OR "Apertuur?" OR "Apertuur"
 OR "?Apertur" OR "Apertur?" OR "Apertur"
 OR "?بؤرة" OR "بؤرة?" OR "بؤرة"
 OR "OTOMATİK ÇERÇEVELEME*" OR "?OTOMATİK ÇERÇEVELEME" OR "OTOMATİKÇERÇEVELEME" OR "?OTOMATİKÇERÇEVELEME" OR "OTOMATİKÇERÇEVELEME?" OR "#OTOMATİKÇERÇEVELEME"
 OR "*自動追蹤主體*" OR "*自動追蹤主體*"
 OR "ENCUADRE AUTOMÁTICO*" OR "?ENCUADRE AUTOMÁTICO" OR "ENCUADREAUTOMÁTICO" OR "?ENCUADREAUTOMÁTICO" OR "ENCUADREAUTOMÁTICO?" OR "#ENCUADREAUTOMÁTICO"
 OR "АВТОФОКУСИРОВКА НА ДВИЖУЩИХСЯ ОБЪЕКТАХ*" OR "?АВТОФОКУСИРОВКА НА ДВИЖУЩИХСЯ ОБЪЕКТАХ" OR "АВТОФОКУСИРОВКАНАДВИЖУЩИХСЯОБЪЕКТАХ" OR "?АВТОФОКУСИРОВКАНАДВИЖУЩИХСЯОБЪЕКТАХ" OR "АВТОФОКУСИРОВКАНАДВИЖУЩИХСЯОБЪЕКТАХ?" OR "#АВТОФОКУСИРОВКАНАДВИЖУЩИХСЯОБЪЕКТАХ"
 OR "ENQUADRAMENTO AUTOMÁTICO*" OR "?ENQUADRAMENTO AUTOMÁTICO" OR "ENQUADRAMENTOAUTOMÁTICO" OR "?ENQUADRAMENTOAUTOMÁTICO" OR "ENQUADRAMENTOAUTOMÁTICO?" OR "#ENQUADRAMENTOAUTOMÁTICO"
 OR "자동 프레이밍*" OR "?자동 프레이밍" OR "자동프레이밍" OR "?자동프레이밍" OR "자동프레이밍?" OR "#자동프레이밍"
 OR "오토 프레이밍*" OR "?오토 프레이밍" OR "오토프레이밍" OR "?오토프레이밍" OR "오토프레이밍?" OR "#오토프레이밍"
 OR "*自動フレーミング*" OR "*自動フレーミング*"
 OR "INQUADRATURA AUTOMATICA*" OR "?INQUADRATURA AUTOMATICA" OR "INQUADRATURAAUTOMATICA" OR "?INQUADRATURAAUTOMATICA" OR "INQUADRATURAAUTOMATICA?" OR "#INQUADRATURAAUTOMATICA"
 OR "Auto Framing*" OR "?Auto Framing" OR "AutoFraming" OR "?AutoFraming" OR "AutoFraming?" OR "#AutoFraming"
 OR "*自动构图*" OR "*自动构图*"
 OR "إعداد الصورة آلياً*" OR "?إعداد الصورة آلياً" OR "إعدادالصورةآلياً" OR "?إعدادالصورةآلياً" OR "إعدادالصورةآلياً?" OR "#إعدادالصورةآلياً"
 OR "?Autofokus" OR "Autofokus?" OR "Autofokus" OR "Autofokus?" OR "?Autofokus"
 OR "?오토 포커스" OR "오토 포커스?" OR "오토포커스" OR "오토포커스?" OR "?오토포커스"
 OR "?자동 포커스" OR "자동 포커스?" OR "자동포커스" OR "자동포커스?" OR "?자동포커스"
 OR "?Auto focus" OR "Auto focus?" OR "Autofocus" OR "Autofocus?" OR "?Autofocus"
 OR "?Auto-focus" OR "Auto-focus?" OR "Auto-focus" OR "Auto-focus?" OR "?Auto-focus"
 OR "A/F" OR "A/F"
 OR "?Automatische Focus" OR "Automatische Focus?" OR "AutomatischeFocus" OR "AutomatischeFocus?" OR "?AutomatischeFocus"
 OR "?自动聚焦" OR "自动聚焦?" OR "自动聚焦" OR "自动聚焦?" OR "?自动聚焦"
 OR "?background blur" OR "background blur?" OR "backgroundblur" OR "backgroundblur?" OR "?backgroundblur"
 OR "?Blur Effect" OR "Blur Effect?" OR "BlurEffect" OR "BlurEffect?" OR "?BlurEffect"
 OR "?Bokeh" OR "Bokeh?" OR "Bokeh" OR "Bokeh?" OR "?Bokeh"
 OR "*máy ảnh*" OR "*máyảnh*"
 OR "*kamerası*" OR "*kamerası*"
 OR "*相機*" OR "*相機*"
 OR "*ล้อง*" OR "*ล้อง*"
 OR "*CÁMARA*" OR "*CÁMARA*"
 OR "*КАМЕРА*" OR "*КАМЕРА*"
 OR "*CÂMARA*" OR "*CÂMARA*"
 OR "*카메라*" OR "*카메라*"
 OR "*カメラ*" OR "*カメラ*"
 OR "*FOTOCAMERA*" OR "*FOTOCAMERA*"
 OR "*KAMERA*" OR "*KAMERA*"
 OR "*CAMÉRA*" OR "*CAMÉRA*"
 OR "*Appareil photo*" OR "*Appareilphoto*"
 OR "*Camera*" OR "*Camera*"
 OR "*Cameras*" OR "*Cameras*"
 OR "*摄像头*" OR "*摄像头*"
 OR "الكاميرا*" OR "?الكاميرا" OR "الكاميرا" OR "?الكاميرا" OR "الكاميرا?"
 OR "Chế độ capture view*" OR "?Chế độ capture view" OR "Chếđộcaptureview" OR "?Chếđộcaptureview" OR "Chếđộcaptureview?" OR "#Chếđộcaptureview"
 OR "Yakalama görünümü modu*" OR "?Yakalama görünümü modu" OR "Yakalamagörünümümodu" OR "?Yakalamagörünümümodu" OR "Yakalamagörünümümodu?" OR "#Yakalamagörünümümodu"
 OR "*同步拍攝閲覽*" OR "*同步拍攝閲覽*"
 OR "*โหมดมุมมองการจับภาพ*" OR "*โหมดมุมมองการจับภาพ*"
 OR "Modo capture view*" OR "?Modo capture view" OR "Modocaptureview" OR "?Modocaptureview" OR "Modocaptureview?" OR "#Modocaptureview"
 OR "Режим capture view*" OR "?Режим capture view" OR "Режимcaptureview" OR "?Режимcaptureview" OR "Режимcaptureview?" OR "#Режимcaptureview"
 OR "Modo de vista de captura*" OR "?Modo de vista de captura" OR "Mododevistadecaptura" OR "?Mododevistadecaptura" OR "Mododevistadecaptura?" OR "#Mododevistadecaptura"
 OR "퀵 뷰 모드*" OR "?퀵 뷰 모드" OR "퀵뷰모드" OR "?퀵뷰모드" OR "퀵뷰모드?" OR "#퀵뷰모드"
 OR "*キャプチャビューモード*" OR "*キャプチャビューモード*"
 OR "Modalità vista acquisizione*" OR "?Modalità vista acquisizione" OR "Modalitàvistaacquisizione" OR "?Modalitàvistaacquisizione" OR "Modalitàvistaacquisizione?" OR "#Modalitàvistaacquisizione"
 OR "CAPTURE VIEW-MODUS*" OR "?CAPTURE VIEW-MODUS" OR "CAPTUREVIEW-MODUS" OR "?CAPTUREVIEW-MODUS" OR "CAPTUREVIEW-MODUS?" OR "#CAPTUREVIEW-MODUS"
 OR "Capture View*" OR "?Capture View" OR "CaptureView" OR "?CaptureView" OR "CaptureView?" OR "#CaptureView"
 OR "*拍摄&预览模式*" OR "*拍摄&预览模式*"
 OR "وضع عرض اللقطة*" OR "?وضع عرض اللقطة" OR "وضععرضاللقطة" OR "?وضععرضاللقطة" OR "وضععرضاللقطة?" OR "#وضععرضاللقطة"
 OR "Derinlik Görüşü*" OR "?Derinlik Görüşü" OR "DerinlikGörüşü" OR "?DerinlikGörüşü" OR "DerinlikGörüşü?"
 OR "*深度視覺*" OR "*深度視覺*"
 OR "*ระยะความลึกของภาพ*" OR "*ระยะความลึกของภาพ*"
 OR "Visión profunda*" OR "?Visión profunda" OR "Visiónprofunda" OR "?Visiónprofunda" OR "Visiónprofunda?"
 OR "Камера Глубины*" OR "?Камера Глубины" OR "КамераГлубины" OR "?КамераГлубины" OR "КамераГлубины?"
 OR "Visão de Profundidade*" OR "?Visão de Profundidade" OR "VisãodeProfundidade" OR "?VisãodeProfundidade" OR "VisãodeProfundidade?"
 OR "Penglihatan dalam*" OR "?Penglihatan dalam" OR "Penglihatandalam" OR "?Penglihatandalam" OR "Penglihatandalam?"
 OR "뎁스비젼*" OR "?뎁스비젼" OR "뎁스비젼" OR "?뎁스비젼" OR "뎁스비젼?"
 OR "뎁스비전*" OR "?뎁스비전" OR "뎁스비전" OR "?뎁스비전" OR "뎁스비전?"
 OR "Tiefenvision*" OR "?Tiefenvision" OR "Tiefenvision" OR "?Tiefenvision" OR "Tiefenvision?"
 OR "Tiefenblick*" OR "?Tiefenblick" OR "Tiefenblick" OR "?Tiefenblick" OR "Tiefenblick?"
 OR "Vision profonde*" OR "?Vision profonde" OR "Visionprofonde" OR "?Visionprofonde" OR "Visionprofonde?"
 OR "Depth Vision*" OR "?Depth Vision" OR "DepthVision" OR "?DepthVision" OR "DepthVision?"
 OR "Diepte Visie*" OR "?Diepte Visie" OR "DiepteVisie" OR "?DiepteVisie" OR "DiepteVisie?"
 OR "*深度视觉*" OR "*深度视觉*"
 OR "ديبث فيجن*" OR "?ديبث فيجن" OR "ديبثفيجن" OR "?ديبثفيجن" OR "ديبثفيجن?"
 OR "Yönetmen Görünümü*" OR "?Yönetmen Görünümü" OR "YönetmenGörünümü" OR "?YönetmenGörünümü" OR "YönetmenGörünümü?" OR "#YönetmenGörünümü"
 OR "*導演視圖*" OR "*導演視圖*"
 OR "*มุมมองของผู้กำกับ*" OR "*มุมมองของผู้กำกับ*"
 OR "Vista del director*" OR "?Vista del director" OR "Vistadeldirector" OR "?Vistadeldirector" OR "Vistadeldirector?" OR "#Vistadeldirector"
 OR "Режим режиссера*" OR "?Режим режиссера" OR "Режимрежиссера" OR "?Режимрежиссера" OR "Режимрежиссера?" OR "#Режимрежиссера"
 OR "Vista do Realizador*" OR "?Vista do Realizador" OR "VistadoRealizador" OR "?VistadoRealizador" OR "VistadoRealizador?" OR "#VistadoRealizador"
 OR "디렉터스 뷰*" OR "?디렉터스 뷰" OR "디렉터스뷰" OR "?디렉터스뷰" OR "디렉터스뷰?" OR "#디렉터스뷰"
 OR "*ディレクターズビュー*" OR "*ディレクターズビュー*"
 OR "Vista del regista *" OR "?Vista del regista " OR "Vistadelregista " OR "?Vistadelregista " OR "Vistadelregista ?" OR "#Vistadelregista "
 OR "Point de vue du réalisateur*" OR "?Point de vue du réalisateur" OR "Pointdevueduréalisateur" OR "?Pointdevueduréalisateur" OR "Pointdevueduréalisateur?" OR "#Pointdevueduréalisateur"
 OR "Director?s View*" OR "?Director?s View" OR "Director?sView" OR "?Director?sView" OR "Director?sView?" OR "#Director?sView"
 OR "Directors-View*" OR "?Directors-View" OR "Directors-View" OR "?Directors-View" OR "Directors-View?" OR "#Directors-View"
 OR "Directors View*" OR "?Directors View" OR "DirectorsView" OR "?DirectorsView" OR "DirectorsView?" OR "#DirectorsView" OR "#DirectorsView*"
 OR "*导演视角*" OR "*导演视角*"
 OR "Tampilan Sutradara*" OR "?Tampilan Sutradara" OR "TampilanSutradara" OR "?TampilanSutradara" OR "TampilanSutradara?" OR "#TampilanSutradara"
 OR "عرض المخرج*" OR "?عرض المخرج" OR "عرضالمخرج" OR "?عرضالمخرج" OR "عرضالمخرج?" OR "#عرضالمخرج"
 OR "*Tính năng dual preview*" OR "*Tínhnăngdualpreview*"
 OR "*Çift önizleme*" OR "*Çiftönizleme*"
 OR "*雙屏預覽*" OR "*雙屏預覽*"
 OR "Vista previa dual*" OR "?Vista previa dual" OR "Vistapreviadual" OR "?Vistapreviadual" OR "Vistapreviadual?" OR "#Vistapreviadual"
 OR "Двойной предпросмотр*" OR "?Двойной предпросмотр" OR "Двойнойпредпросмотр" OR "?Двойнойпредпросмотр" OR "Двойнойпредпросмотр?" OR "#Двойнойпредпросмотр"
 OR "PRÉ-VISUALIZAÇÃO DUPLA*" OR "?PRÉ-VISUALIZAÇÃO DUPLA" OR "PRÉ-VISUALIZAÇÃODUPLA" OR "?PRÉ-VISUALIZAÇÃODUPLA" OR "PRÉ-VISUALIZAÇÃODUPLA?" OR "#PRÉ-VISUALIZAÇÃODUPLA"
 OR "듀얼프리뷰*" OR "?듀얼프리뷰" OR "듀얼프리뷰" OR "?듀얼프리뷰" OR "듀얼프리뷰?" OR "#듀얼프리뷰"
 OR "*デュアルプレビュー*" OR "*デュアルプレビュー*"
 OR "Doppia anteprima*" OR "?Doppia anteprima" OR "Doppiaanteprima" OR "?Doppiaanteprima" OR "Doppiaanteprima?" OR "#Doppiaanteprima"
 OR "DUAL-VORSCHAU*" OR "?DUAL-VORSCHAU" OR "DUAL-VORSCHAU" OR "?DUAL-VORSCHAU" OR "DUAL-VORSCHAU?" OR "#DUAL-VORSCHAU"
 OR "DUAL VORSCHAU*" OR "?DUAL VORSCHAU" OR "DUALVORSCHAU" OR "?DUALVORSCHAU" OR "DUALVORSCHAU?" OR "#DUALVORSCHAU"
 OR "Dual preview*" OR "?Dual preview" OR "Dualpreview" OR "?Dualpreview" OR "Dualpreview?" OR "#Dualpreview"
 OR "*双重预览*" OR "*双重预览*"
 OR "العرض المسبق المزدوج*" OR "?العرض المسبق المزدوج" OR "العرضالمسبقالمزدوج" OR "?العرضالمسبقالمزدوج" OR "العرضالمسبقالمزدوج?" OR "#العرضالمسبقالمزدوج"
 OR "Camera chế độ flex mode*" OR "?Camera chế độ flex mode" OR "Camerachếđộflexmode" OR "?Camerachếđộflexmode" OR "Camerachếđộflexmode?" OR "#Camerachếđộflexmode"
 OR "Flex mod kamera*" OR "?Flex mod kamera" OR "Flexmodkamera" OR "?Flexmodkamera" OR "Flexmodkamera?" OR "#Flexmodkamera"
 OR "*Flex模式拍攝*" OR "*Flex模式拍攝*"
 OR "*กล้องในโหมด flex*" OR "*กล้องในโหมดflex*"
 OR "Cámara con modo flex*" OR "?Cámara con modo flex" OR "Cámaraconmodoflex" OR "?Cámaraconmodoflex" OR "Cámaraconmodoflex?" OR "#Cámaraconmodoflex"
 OR "Камера в режиме flex*" OR "?Камера в режиме flex" OR "Камераврежимеflex" OR "?Камераврежимеflex" OR "Камераврежимеflex?" OR "#Камераврежимеflex"
 OR "Câmara com modo flex*" OR "?Câmara com modo flex" OR "Câmaracommodoflex" OR "?Câmaracommodoflex" OR "Câmaracommodoflex?" OR "#Câmaracommodoflex"
 OR "플렉스 모드 카메라*" OR "?플렉스 모드 카메라" OR "플렉스모드카메라" OR "?플렉스모드카메라" OR "플렉스모드카메라?" OR "#플렉스모드카메라"
 OR "*フレックスモードカメラ*" OR "*フレックスモードカメラ*"
 OR "Fotocamera in modalità flex*" OR "?Fotocamera in modalità flex" OR "Fotocamerainmodalitàflex" OR "?Fotocamerainmodalitàflex" OR "Fotocamerainmodalitàflex?" OR "#Fotocamerainmodalitàflex"
 OR "Kamera im flex-modus*" OR "?Kamera im flex-modus" OR "Kameraimflex-modus" OR "?Kameraimflex-modus" OR "Kameraimflex-modus?" OR "#Kameraimflex-modus"
 OR "Kamera im flex modus*" OR "?Kamera im flex modus" OR "Kameraimflexmodus" OR "?Kameraimflexmodus" OR "Kameraimflexmodus?" OR "#Kameraimflexmodus"
 OR "Appareil photo en mode flex*" OR "?Appareil photo en mode flex" OR "Appareilphotoenmodeflex" OR "?Appareilphotoenmodeflex" OR "Appareilphotoenmodeflex?" OR "#Appareilphotoenmodeflex"
 OR "Flex Mode Camera*" OR "?Flex Mode Camera" OR "FlexModeCamera" OR "?FlexModeCamera" OR "FlexModeCamera?" OR "#FlexModeCamera"
 OR "Flex-Mode Camera*" OR "?Flex-Mode Camera" OR "Flex-ModeCamera" OR "?Flex-ModeCamera" OR "Flex-ModeCamera?" OR "#Flex-ModeCamera"
 OR "Flex-modus camera*" OR "?Flex-modus camera" OR "Flex-moduscamera" OR "?Flex-moduscamera" OR "Flex-moduscamera?" OR "#Flex-moduscamera"
 OR "Flex modus camera*" OR "?Flex modus camera" OR "Flexmoduscamera" OR "?Flexmoduscamera" OR "Flexmoduscamera?" OR "#Flexmoduscamera"
 OR "*自适应分屏模式拍摄*" OR "*自适应分屏模式拍摄*"
 OR "كاميرا بالوضع المرن*" OR "?كاميرا بالوضع المرن" OR "كاميرابالوضعالمرن" OR "?كاميرابالوضعالمرن" OR "كاميرابالوضعالمرن?" OR "#كاميرابالوضعالمرن"
 OR "FPS" OR "FPS"
 OR "Frame Rate*" OR "?Frame Rate" OR "FrameRate"
 OR "Frame Rates*" OR "?Frame Rates" OR "FrameRates"
 OR "?120 fps" OR "120fps" OR "120fps?" OR "?120fps"
 OR "?60 fps" OR "60fps" OR "60fps?" OR "?60fps"
 OR "?24 fps" OR "24fps" OR "24fps?" OR "?24fps"
 OR "*自拍相機*" OR "*自拍相機*"
 OR "*正面相機*" OR "*正面相機*"
 OR "*กล้องถ่ายตัวเอง*" OR "*กล้องถ่ายตัวเอง*"
 OR "*กล้องหน้า*" OR "*กล้องหน้า*"
 OR "фронтальнаякамера*" OR "?фронтальнаякамера" OR "фронтальнаякамера" OR "?фронтальнаякамера" OR "фронтальнаякамера?"
 OR "камерадляселфи*" OR "?камерадляселфи" OR "камерадляселфи" OR "?камерадляселфи" OR "камерадляселфи?"
 OR "фронтальнаякаме*" OR "?фронтальнаякаме" OR "фронтальнаякаме" OR "?фронтальнаякаме" OR "фронтальнаякаме?"
 OR "câmarafrontal*" OR "?câmarafrontal" OR "câmarafrontal" OR "?câmarafrontal" OR "câmarafrontal?"
 OR "전면카메라*" OR "?전면카메라" OR "전면카메라" OR "?전면카메라" OR "전면카메라?"
 OR "셀피카메라*" OR "?셀피카메라" OR "셀피카메라" OR "?셀피카메라" OR "셀피카메라?"
 OR "*セルフカメラ*" OR "*セルフカメラ*"
 OR "*前面カメラ*" OR "*前面カメラ*"
 OR "Frontkamera*" OR "?Frontkamera" OR "Frontkamera" OR "?Frontkamera" OR "Frontkamera?"
 OR "Selbstkamera*" OR "?Selbstkamera" OR "Selbstkamera" OR "?Selbstkamera" OR "Selbstkamera?"
 OR "*前置摄像头*" OR "*前置摄像头*"
 OR "kameradepan*" OR "?kameradepan" OR "kameradepan" OR "?kameradepan" OR "kameradepan?"
 OR "?HDR 10+" OR "HDR 10+?" OR "HDR10+" OR "HDR10+?" OR "?HDR10+" OR "#HDR10+"
 OR "?HDR10 Plus" OR "HDR10 Plus?" OR "HDR10Plus" OR "HDR10Plus?" OR "?HDR10Plus" OR "#HDR10Plus"
 OR "trôi nhanh*" OR "?trôi nhanh" OR "trôinhanh" OR "?trôinhanh" OR "trôinhanh?" OR "#trôinhanh"
 OR "video hızlandırma*" OR "?video hızlandırma" OR "videohızlandırma" OR "?videohızlandırma" OR "videohızlandırma?" OR "#videohızlandırma"
 OR "*動態縮時攝影*" OR "*動態縮時攝影*"
 OR "*ไฮเปอร์แลปส์*" OR "*ไฮเปอร์แลปส์*"
 OR "hiperlapso*" OR "?hiperlapso" OR "hiperlapso" OR "?hiperlapso" OR "hiperlapso?" OR "#hiperlapso"
 OR "гиперлапс*" OR "?гиперлапс" OR "гиперлапс" OR "?гиперлапс" OR "гиперлапс?" OR "#гиперлапс"
 OR "hiper-selang*" OR "?hiper-selang" OR "hiper-selang" OR "?hiper-selang" OR "hiper-selang?" OR "#hiper-selang"
 OR "하이퍼랩스*" OR "?하이퍼랩스" OR "하이퍼랩스" OR "?하이퍼랩스" OR "하이퍼랩스?" OR "#하이퍼랩스"
 OR "나이트하이퍼랩스*" OR "?나이트하이퍼랩스" OR "나이트하이퍼랩스" OR "?나이트하이퍼랩스" OR "나이트하이퍼랩스?" OR "#나이트하이퍼랩스"
 OR "*ハイパーラプス*" OR "*ハイパーラプス*"
 OR "hyperlapse*" OR "?hyperlapse" OR "hyperlapse" OR "?hyperlapse" OR "hyperlapse?" OR "#hyperlapse"
 OR "hyper-lapse*" OR "?hyper-lapse" OR "hyper-lapse" OR "?hyper-lapse" OR "hyper-lapse?" OR "#hyper-lapse"
 OR "Night Hyperlapse*" OR "?Night Hyperlapse" OR "NightHyperlapse" OR "?NightHyperlapse" OR "NightHyperlapse?" OR "#NightHyperlapse"
 OR "Night-Hyperlapse*" OR "?Night-Hyperlapse" OR "Night-Hyperlapse" OR "?Night-Hyperlapse" OR "Night-Hyperlapse?" OR "#Night-Hyperlapse"
 OR "*延时摄影*" OR "*延时摄影*"
 OR "*هايبرلابس*" OR "*هايبرلابس*"
 OR "Ống kính" OR "Ốngkính"
 OR "鏡頭" OR "鏡頭"
 OR "เลนส์" OR "เลนส์"
 OR "Lentes" OR "Lentes"
 OR "Объектив" OR "Объектив"
 OR "Lente" OR "Lente"
 OR "Kanta" OR "Kanta"
 OR "렌즈" OR "렌즈"
 OR "レンズ" OR "レンズ"
 OR "Linse" OR "Linse"
 OR "Objectif" OR "Objectif"
 OR "Lens" OR "Lens"
 OR "镜头" OR "镜头"
 OR "Lensa" OR "Lensa"
 OR "عدسة" OR "عدسة"
 OR "Lấy nét động*" OR "?Lấy nét động" OR "Lấynétđộng" OR "?Lấynétđộng" OR "Lấynétđộng?" OR "#Lấynétđộng"
 OR "Canlı Odak*" OR "?Canlı Odak" OR "CanlıOdak" OR "?CanlıOdak" OR "CanlıOdak?" OR "#CanlıOdak"
 OR "*景深特效攝影*" OR "*景深特效攝影*"
 OR "*景深即時預覽影*" OR "*景深即時預覽影*"
 OR "ЖИВЫМ ФОКУСОМ*" OR "?ЖИВЫМ ФОКУСОМ" OR "ЖИВЫМФОКУСОМ" OR "?ЖИВЫМФОКУСОМ" OR "ЖИВЫМФОКУСОМ?" OR "#ЖИВЫМФОКУСОМ"
 OR "Foco ao Vivo*" OR "?Foco ao Vivo" OR "FocoaoVivo" OR "?FocoaoVivo" OR "FocoaoVivo?" OR "#FocoaoVivo"
 OR "Fokus langsung*" OR "?Fokus langsung" OR "Fokuslangsung" OR "?Fokuslangsung" OR "Fokuslangsung?" OR "#Fokuslangsung"
 OR "라이브 포커스*" OR "?라이브 포커스" OR "라이브포커스" OR "?라이브포커스" OR "라이브포커스?" OR "#라이브포커스"
 OR "ライブフォーカス*" OR "?ライブフォーカス" OR "ライブフォーカス" OR "?ライブフォーカス" OR "ライブフォーカス?" OR "#ライブフォーカス"
 OR "FUOCO LIVE*" OR "?FUOCO LIVE" OR "FUOCOLIVE" OR "?FUOCOLIVE" OR "FUOCOLIVE?" OR "#FUOCOLIVE"
 OR "MISE AU POINT EN DIRECT*" OR "?MISE AU POINT EN DIRECT" OR "MISEAUPOINTENDIRECT" OR "?MISEAUPOINTENDIRECT" OR "MISEAUPOINTENDIRECT?" OR "#MISEAUPOINTENDIRECT"
 OR "Live Focus*" OR "?Live Focus" OR "LiveFocus" OR "?LiveFocus" OR "LiveFocus?" OR "#LiveFocus"
 OR "*实时虚化视频*" OR "*实时虚化视频*"
 OR "التركيز المباشر*" OR "?التركيز المباشر" OR "التركيزالمباشر" OR "?التركيزالمباشر" OR "التركيزالمباشر?" OR "#التركيزالمباشر"
 OR "Live-focus video*" OR "?Live-focus video" OR "Live-focusvideo" OR "?Live-focusvideo" OR "Live-focusvideo?" OR "#Live-focusvideo"
 OR "Livefocus video*" OR "?Livefocus video" OR "Livefocusvideo" OR "?Livefocusvideo" OR "Livefocusvideo?" OR "#Livefocusvideo"
 OR "Ánh sáng yếu*" OR "?Ánh sáng yếu" OR "Ánhsángyếu" OR "?Ánhsángyếu" OR "Ánhsángyếu?"
 OR "Düşük Işık*" OR "?Düşük Işık" OR "DüşükIşık" OR "?DüşükIşık" OR "DüşükIşık?"
 OR "低光線*" OR "?低光線" OR "低光線" OR "?低光線" OR "低光線?"
 OR "แสงต่ำ*" OR "?แสงต่ำ" OR "แสงต่ำ" OR "?แสงต่ำ" OR "แสงต่ำ?"
 OR "Luz baja*" OR "?Luz baja" OR "Luzbaja" OR "?Luzbaja" OR "Luzbaja?"
 OR "Тусклое освещение*" OR "?Тусклое освещение" OR "Тусклоеосвещение" OR "?Тусклоеосвещение" OR "Тусклоеосвещение?"
 OR "Baixa luminosidade*" OR "?Baixa luminosidade" OR "Baixaluminosidade" OR "?Baixaluminosidade" OR "Baixaluminosidade?"
 OR "Cahaya Rendah*" OR "?Cahaya Rendah" OR "CahayaRendah" OR "?CahayaRendah" OR "CahayaRendah?"
 OR "저조도*" OR "?저조도" OR "저조도" OR "?저조도" OR "저조도?"
 OR "Luce bassa*" OR "?Luce bassa" OR "Lucebassa" OR "?Lucebassa" OR "Lucebassa?"
 OR "Schwaches Licht*" OR "?Schwaches Licht" OR "SchwachesLicht" OR "?SchwachesLicht" OR "SchwachesLicht?"
 OR "Faible luminosité*" OR "?Faible luminosité" OR "Faibleluminosité" OR "?Faibleluminosité" OR "Faibleluminosité?"
 OR "Low Light*" OR "?Low Light" OR "LowLight" OR "?LowLight" OR "LowLight?"
 OR "Low-Light*" OR "?Low-Light" OR "Low-Light" OR "?Low-Light" OR "Low-Light?"
 OR "Weinig Licht*" OR "?Weinig Licht" OR "WeinigLicht" OR "?WeinigLicht" OR "WeinigLicht?"
 OR "低亮度*" OR "?低亮度" OR "低亮度" OR "?低亮度" OR "低亮度?"
 OR "Cahaya remang*" OR "?Cahaya remang" OR "Cahayaremang" OR "?Cahayaremang" OR "Cahayaremang?"
 OR "ضوء منخفض*" OR "?ضوء منخفض" OR "ضوءمنخفض" OR "?ضوءمنخفض" OR "ضوءمنخفض?"
 OR "*萬像素*" OR "*萬像素*"
 OR "*เมกะพิกเซล*" OR "*เมกะพิกเซล*"
 OR "*megapíxel*" OR "*megapíxel*"
 OR "*мегапиксельная*" OR "*мегапиксельная*"
 OR "*мегапикселей*" OR "*мегапикселей*"
 OR "*메가픽셀*" OR "*메가픽셀*"
 OR "*メガピクセル*" OR "*メガピクセル*"
 OR "*mégapixel*" OR "*mégapixel*"
 OR "*Megapixel*" OR "*Megapixel*"
 OR "*megapíxeis*" OR "*megapíxeis*"
 OR "*Mega-pixel*" OR "*Mega-pixel*"
 OR "*万像素*" OR "*万像素*"
 OR "CHẾ ĐỘ CHỤP ĐÊM*" OR "?CHẾ ĐỘ CHỤP ĐÊM" OR "CHẾĐỘCHỤPĐÊM" OR "?CHẾĐỘCHỤPĐÊM" OR "CHẾĐỘCHỤPĐÊM?" OR "#CHẾĐỘCHỤPĐÊM"
 OR "GECE MODU*" OR "?GECE MODU" OR "GECEMODU" OR "?GECEMODU" OR "GECEMODU?" OR "#GECEMODU"
 OR "*夜間模式*" OR "*夜間模式*"
 OR "*โหมดกลางคืน*" OR "*โหมดกลางคืน*"
 OR "MODO NOCTURNO*" OR "?MODO NOCTURNO" OR "MODONOCTURNO" OR "?MODONOCTURNO" OR "MODONOCTURNO?" OR "#MODONOCTURNO"
 OR "НОЧНОЙ РЕЖИМ*" OR "?НОЧНОЙ РЕЖИМ" OR "НОЧНОЙРЕЖИМ" OR "?НОЧНОЙРЕЖИМ" OR "НОЧНОЙРЕЖИМ?" OR "#НОЧНОЙРЕЖИМ"
 OR "НІЧНИЙ РЕЖИМ*" OR "?НІЧНИЙ РЕЖИМ" OR "НІЧНИЙРЕЖИМ" OR "?НІЧНИЙРЕЖИМ" OR "НІЧНИЙРЕЖИМ?" OR "#НІЧНИЙРЕЖИМ"
 OR "MODO NOTURNO*" OR "?MODO NOTURNO" OR "MODONOTURNO" OR "?MODONOTURNO" OR "MODONOTURNO?" OR "#MODONOTURNO"
 OR "야간 모드*" OR "?야간 모드" OR "야간모드" OR "?야간모드" OR "야간모드?" OR "#야간모드"
 OR "나이트 모드*" OR "?나이트 모드" OR "나이트모드" OR "?나이트모드" OR "나이트모드?" OR "#나이트모드"
 OR "브라이트 나이트*" OR "?브라이트 나이트" OR "브라이트나이트" OR "?브라이트나이트" OR "브라이트나이트?" OR "#브라이트나이트"
 OR "ナイトモード*" OR "?ナイトモード" OR "ナイトモード" OR "?ナイトモード" OR "ナイトモード?" OR "#ナイトモード"
 OR "MODALITÀ NOTTE*" OR "?MODALITÀ NOTTE" OR "MODALITÀNOTTE" OR "?MODALITÀNOTTE" OR "MODALITÀNOTTE?" OR "#MODALITÀNOTTE"
 OR "NACHTMODUS*" OR "?NACHTMODUS" OR "NACHTMODUS" OR "?NACHTMODUS" OR "NACHTMODUS?" OR "#NACHTMODUS"
 OR "mode Nuit*" OR "?mode Nuit" OR "modeNuit" OR "?modeNuit" OR "modeNuit?" OR "#modeNuit"
 OR "Night Mode*" OR "?Night Mode" OR "NightMode" OR "?NightMode" OR "NightMode?" OR "#NightMode"
 OR "Bright Night*" OR "?Bright Night" OR "BrightNight" OR "?BrightNight" OR "BrightNight?" OR "#BrightNight"
 OR "*夜间模式*" OR "*夜间模式*"
 OR "Gece Modu"
 OR "الوضع الليلي*" OR "?الوضع الليلي" OR "الوضعالليلي" OR "?الوضعالليلي" OR "الوضعالليلي?" OR "#الوضعالليلي"
 OR "Chống rung quang học*" OR "?Chống rung quang học" OR "Chốngrungquanghọc" OR "?Chốngrungquanghọc" OR "Chốngrungquanghọc?"
 OR "Optik Görüntü Sabitleyici*" OR "?Optik Görüntü Sabitleyici" OR "OptikGörüntüSabitleyici" OR "?OptikGörüntüSabitleyici" OR "OptikGörüntüSabitleyici?"
 OR "*光學影像穩定功能*" OR "*光學影像穩定功能*"
 OR "*ระบบกันภาพสั่น*" OR "*ระบบกันภาพสั่น*"
 OR "Estabilizador de imagen óptico*" OR "?Estabilizador de imagen óptico" OR "Estabilizadordeimagenóptico" OR "?Estabilizadordeimagenóptico" OR "Estabilizadordeimagenóptico?"
 OR "Estabilizador de imagem ótima*" OR "?Estabilizador de imagem ótima" OR "Estabilizadordeimagemótima" OR "?Estabilizadordeimagemótima" OR "Estabilizadordeimagemótima?"
 OR "Penstabilan Imej Optik*" OR "?Penstabilan Imej Optik" OR "PenstabilanImejOptik" OR "?PenstabilanImejOptik" OR "PenstabilanImejOptik?"
 OR "Penstabil Gambar Optik*" OR "?Penstabil Gambar Optik" OR "PenstabilGambarOptik" OR "?PenstabilGambarOptik" OR "PenstabilGambarOptik?"
 OR "*光学式手ブレ補正*" OR "*光学式手ブレ補正*"
 OR "Stabilizzatore ottico immagine*" OR "?Stabilizzatore ottico immagine" OR "Stabilizzatoreotticoimmagine" OR "?Stabilizzatoreotticoimmagine" OR "Stabilizzatoreotticoimmagine?"
 OR "Optischer Bildstabilisator*" OR "?Optischer Bildstabilisator" OR "OptischerBildstabilisator" OR "?OptischerBildstabilisator" OR "OptischerBildstabilisator?"
 OR "Stabilisateur d'image optique*" OR "?Stabilisateur d'image optique" OR "Stabilisateurd'imageoptique" OR "?Stabilisateurd'imageoptique" OR "Stabilisateurd'imageoptique?"
 OR "OIS" OR "OIS"
 OR "Optical Image Stabilizer*" OR "?Optical Image Stabilizer" OR "OpticalImageStabilizer" OR "?OpticalImageStabilizer" OR "OpticalImageStabilizer?"
 OR "Optical Image Stabilization*" OR "?Optical Image Stabilization" OR "OpticalImageStabilization" OR "?OpticalImageStabilization" OR "OpticalImageStabilization?"
 OR "Optische beeldstabilisatie*" OR "?Optische beeldstabilisatie" OR "Optischebeeldstabilisatie" OR "?Optischebeeldstabilisatie" OR "Optischebeeldstabilisatie?"
 OR "Optische Beeld Stabilisatie*" OR "?Optische Beeld Stabilisatie" OR "OptischeBeeldStabilisatie" OR "?OptischeBeeldStabilisatie" OR "OptischeBeeldStabilisatie?"
 OR "*光学防抖*" OR "*光学防抖*"
 OR "ออกนอกโฟกัส*" OR "?ออกนอกโฟกัส" OR "ออกนอกโฟกัส" OR "?ออกนอกโฟกัส" OR "ออกนอกโฟกัส?"
 OR "?Fueradeenfoque" OR "Fueradeenfoque?" OR "Fueradeenfoque" OR "Fueradeenfoque?" OR "?Fueradeenfoque"
 OR "?Fora de foco" OR "Fora de foco?" OR "Foradefoco" OR "Foradefoco?" OR "?Foradefoco"
 OR "?FokusKeluar" OR "FokusKeluar?" OR "FokusKeluar" OR "FokusKeluar?" OR "?FokusKeluar"
 OR "?アウトフォーカス" OR "アウトフォーカス?" OR "アウトフォーカス" OR "アウトフォーカス?" OR "?アウトフォーカス"
 OR "?Hors mise au point" OR "Hors mise au point?" OR "Horsmiseaupoint" OR "Horsmiseaupoint?" OR "?Horsmiseaupoint"
 OR "?Outfocus" OR "Outfocus?" OR "Outfocus" OR "Outfocus?" OR "?Outfocus"
 OR "?Out-focus" OR "Out-focus?" OR "Out-focus" OR "Out-focus?" OR "?Out-focus"
 OR "?Uit Focus" OR "Uit Focus?" OR "UitFocus" OR "UitFocus?" OR "?UitFocus"
 OR "?失焦" OR "失焦?" OR "失焦" OR "失焦?" OR "?失焦"
 OR "?pikseller" OR "pikseller?" OR "pikseller" OR "pikseller?" OR "?pikseller"
 OR "像素*" OR "?像素" OR "像素" OR "?像素" OR "像素?"
 OR "จุดภาพ*" OR "?จุดภาพ" OR "จุดภาพ" OR "?จุดภาพ" OR "จุดภาพ?"
 OR "พิกเซล*" OR "?พิกเซล" OR "พิกเซล" OR "?พิกเซล" OR "พิกเซล?"
 OR "?píxel" OR "píxel?" OR "píxel" OR "píxel?" OR "?píxel"
 OR "?píxeles" OR "píxeles?" OR "píxeles" OR "píxeles?" OR "?píxeles"
 OR "?пиксельная" OR "пиксельная?" OR "пиксельная" OR "пиксельная?" OR "?пиксельная"
 OR "?píxeis" OR "píxeis?" OR "píxeis" OR "píxeis?" OR "?píxeis"
 OR "?픽셀" OR "픽셀?" OR "픽셀" OR "픽셀?" OR "?픽셀"
 OR "ピクセル*" OR "?ピクセル" OR "ピクセル" OR "?ピクセル" OR "ピクセル?"
 OR "?Pixel" OR "Pixel?" OR "Pixel" OR "Pixel?" OR "?Pixel"
 OR "?Pixels" OR "Pixels?" OR "Pixels" OR "Pixels?" OR "?Pixels"
 OR "?piksel" OR "piksel?" OR "piksel" OR "piksel?" OR "?piksel"
 OR "?بيكسلات" OR "بيكسلات?" OR "بيكسلات" OR "بيكسلات?" OR "?بيكسلات"
 OR "?chân dung" OR "chân dung?" OR "chândung" OR "chândung?" OR "?chândung"
 OR "?portre" OR "portre?" OR "portre" OR "portre?" OR "?portre"
 OR "人像*" OR "?人像" OR "人像" OR "?人像" OR "人像?"
 OR "ภาพบุคคล*" OR "?ภาพบุคคล" OR "ภาพบุคคล" OR "?ภาพบุคคล" OR "ภาพบุคคล?"
 OR "?Retrato" OR "Retrato?" OR "Retrato" OR "Retrato?" OR "?Retrato"
 OR "?Портретный" OR "Портретный?" OR "Портретный" OR "Портретный?" OR "?Портретный"
 OR "?Портрет" OR "Портрет?" OR "Портрет" OR "Портрет?" OR "?Портрет"
 OR "?인물 사진" OR "인물 사진?" OR "인물사진" OR "인물사진?" OR "?인물사진"
 OR "*ポートレート*" OR "*ポートレート*"
 OR "?Ritratto" OR "Ritratto?" OR "Ritratto" OR "Ritratto?" OR "?Ritratto"
 OR "?Porträt" OR "Porträt?" OR "Porträt" OR "Porträt?" OR "?Porträt"
 OR "?Portrait" OR "Portrait?" OR "Portrait" OR "Portrait?" OR "?Portrait"
 OR "?Portret" OR "Portret?" OR "Portret" OR "Portret?" OR "?Portret"
 OR "肖像*" OR "?肖像" OR "肖像" OR "?肖像" OR "肖像?"
 OR "?potret" OR "potret?" OR "potret" OR "potret?" OR "?potret"
 OR "?بورتريه" OR "بورتريه?" OR "بورتريه" OR "بورتريه?" OR "?بورتريه"
 OR "Đẳng Cấp Chân dung*" OR "?Đẳng Cấp Chân dung" OR "ĐẳngCấpChândung" OR "?ĐẳngCấpChândung" OR "ĐẳngCấpChândung?" OR "#ĐẳngCấpChândung"
 OR "Portre modu*" OR "?Portre modu" OR "Portremodu" OR "?Portremodu" OR "Portremodu?" OR "#Portremodu"
 OR "?Portre modu*" OR "??Portre modu" OR "?Portremodu" OR "??Portremodu" OR "?Portremodu?" OR "#?Portremodu"
 OR "*人像模式*" OR "*人像模式*"
 OR "*โหมดภาพถ่ายบุคคลแบบ*" OR "*โหมดภาพถ่ายบุคคลแบบ*"
 OR "Портретный режим*" OR "?Портретный режим" OR "Портретныйрежим" OR "?Портретныйрежим" OR "Портретныйрежим?" OR "#Портретныйрежим"
 OR "Режим Портрет*" OR "?Режим Портрет" OR "РежимПортрет" OR "?РежимПортрет" OR "РежимПортрет?" OR "#РежимПортрет"
 OR "modo Retrato*" OR "?modo Retrato" OR "modoRetrato" OR "?modoRetrato" OR "modoRetrato?" OR "#modoRetrato"
 OR "modpotret*" OR "?modpotret" OR "modpotret" OR "?modpotret" OR "modpotret?" OR "#modpotret"
 OR "인물 모드*" OR "?인물 모드" OR "인물모드" OR "?인물모드" OR "인물모드?" OR "#인물모드"
 OR "*ポートレートモード*" OR "*ポートレートモード*"
 OR "modalità Ritratto*" OR "?modalità Ritratto" OR "modalitàRitratto" OR "?modalitàRitratto" OR "modalitàRitratto?" OR "#modalitàRitratto"
 OR "Porträt-Modus*" OR "?Porträt-Modus" OR "Porträt-Modus" OR "?Porträt-Modus" OR "Porträt-Modus?" OR "#Porträt-Modus"
 OR "mode Portrait*" OR "?mode Portrait" OR "modePortrait" OR "?modePortrait" OR "modePortrait?" OR "#modePortrait"
 OR "Portrait Mode*" OR "?Portrait Mode" OR "PortraitMode" OR "?PortraitMode" OR "PortraitMode?" OR "#PortraitMode"
 OR "Portretmodus*" OR "?Portretmodus" OR "Portretmodus" OR "?Portretmodus" OR "Portretmodus?" OR "#Portretmodus"
 OR "*肖像模式*" OR "*肖像模式*"
 OR "وضعية Portraitال*" OR "?وضعية Portraitال" OR "وضعيةPortraitال" OR "?وضعيةPortraitال" OR "وضعيةPortraitال?" OR "#وضعيةPortraitال"
 OR "PROFESYONEL MOD*" OR "?PROFESYONEL MOD" OR "PROFESYONELMOD" OR "?PROFESYONELMOD" OR "PROFESYONELMOD?" OR "#PROFESYONELMOD"
 OR "*專業模式*" OR "*專業模式*"
 OR "*โหมดโปร ทำ*" OR "*โหมดโปรทำ*"
 OR "modo Pro*" OR "?modo Pro" OR "modoPro" OR "?modoPro" OR "modoPro?" OR "#modoPro"
 OR "Профессиональный режим*" OR "?Профессиональный режим" OR "Профессиональныйрежим" OR "?Профессиональныйрежим" OR "Профессиональныйрежим?" OR "#Профессиональныйрежим"
 OR "modpro*" OR "?modpro" OR "modpro" OR "?modpro" OR "modpro?" OR "#modpro"
 OR "프로 모드*" OR "?프로 모드" OR "프로모드" OR "?프로모드" OR "프로모드?" OR "#프로모드"
 OR "modalità Pro*" OR "?modalità Pro" OR "modalitàPro" OR "?modalitàPro" OR "modalitàPro?" OR "#modalitàPro"
 OR "Der Pro-Mode*" OR "?Der Pro-Mode" OR "DerPro-Mode" OR "?DerPro-Mode" OR "DerPro-Mode?" OR "#DerPro-Mode"
 OR "Pro Mode*" OR "?Pro Mode" OR "ProMode" OR "?ProMode" OR "ProMode?" OR "#ProMode"
 OR "Pro-mode*" OR "?Pro-mode" OR "Pro-mode" OR "?Pro-mode" OR "Pro-mode?" OR "#Pro-mode"
 OR "*专业模式*" OR "*专业模式*"
 OR "وضع التصوير الاحترافي*" OR "?وضع التصوير الاحترافي" OR "وضعالتصويرالاحترافي" OR "?وضعالتصويرالاحترافي" OR "وضعالتصويرالاحترافي?" OR "#وضعالتصويرالاحترافي"
 OR "*專業影片模式*" OR "*專業影片模式*"
 OR "*โหมดวิดีโอโปร*" OR "*โหมดวิดีโอโปร*"
 OR "Vídeo profesional*" OR "?Vídeo profesional" OR "Vídeoprofesional" OR "?Vídeoprofesional" OR "Vídeoprofesional?" OR "#Vídeoprofesional"
 OR "видео профессионального уровня*" OR "?видео профессионального уровня" OR "видеопрофессиональногоуровня" OR "?видеопрофессиональногоуровня" OR "видеопрофессиональногоуровня?" OR "#видеопрофессиональногоуровня"
 OR "Відео Pro*" OR "?Відео Pro" OR "ВідеоPro" OR "?ВідеоPro" OR "ВідеоPro?" OR "#ВідеоPro"
 OR "Vídeo profissional*" OR "?Vídeo profissional" OR "Vídeoprofissional" OR "?Vídeoprofissional" OR "Vídeoprofissional?" OR "#Vídeoprofissional"
 OR "프로 동영상*" OR "?프로 동영상" OR "프로동영상" OR "?프로동영상" OR "프로동영상?" OR "#프로동영상"
 OR "프로 비디오*" OR "?프로 비디오" OR "프로비디오" OR "?프로비디오" OR "프로비디오?" OR "#프로비디오"
 OR "Video professionali*" OR "?Video professionali" OR "Videoprofessionali" OR "?Videoprofessionali" OR "Videoprofessionali?" OR "#Videoprofessionali"
 OR "professionelle Ansprüche*" OR "?professionelle Ansprüche" OR "professionelleAnsprüche" OR "?professionelleAnsprüche" OR "professionelleAnsprüche?" OR "#professionelleAnsprüche"
 OR "PROFI-VIDEO*" OR "?PROFI-VIDEO" OR "PROFI-VIDEO" OR "?PROFI-VIDEO" OR "PROFI-VIDEO?" OR "#PROFI-VIDEO"
 OR "PROFI VIDEO*" OR "?PROFI VIDEO" OR "PROFIVIDEO" OR "?PROFIVIDEO" OR "PROFIVIDEO?" OR "#PROFIVIDEO"
 OR "vidéos professionnelle*" OR "?vidéos professionnelle" OR "vidéosprofessionnelle" OR "?vidéosprofessionnelle" OR "vidéosprofessionnelle?" OR "#vidéosprofessionnelle"
 OR "Vidéo Pro *" OR "?Vidéo Pro " OR "VidéoPro " OR "?VidéoPro " OR "VidéoPro ?" OR "#VidéoPro "
 OR "Pro Video*" OR "?Pro Video" OR "ProVideo" OR "?ProVideo" OR "ProVideo?" OR "#ProVideo"
 OR "*专业视频模式*" OR "*专业视频模式*"
 OR "Video Pro*" OR "?Video Pro" OR "VideoPro" OR "?VideoPro" OR "VideoPro?" OR "#VideoPro"
 OR "تصوير فيديو احترافي*" OR "?تصوير فيديو احترافي" OR "تصويرفيديواحترافي" OR "?تصويرفيديواحترافي" OR "تصويرفيديواحترافي?" OR "#تصويرفيديواحترافي"
 OR "Tính năng selfie bằng cụm camera sau*" OR "?Tính năng selfie bằng cụm camera sau" OR "Tínhnăngselfiebằngcụmcamerasau" OR "?Tínhnăngselfiebằngcụmcamerasau" OR "Tínhnăngselfiebằngcụmcamerasau?" OR "#Tínhnăngselfiebằngcụmcamerasau"
 OR "Arka kamera selfie'si*" OR "?Arka kamera selfie'si" OR "Arkakameraselfie'si" OR "?Arkakameraselfie'si" OR "Arkakameraselfie'si?" OR "#Arkakameraselfie'si"
 OR "*機背鏡頭自拍*" OR "*機背鏡頭自拍*"
 OR "*กล้องเซลฟี่ด้านหลัง*" OR "*กล้องเซลฟี่ด้านหลัง*"
 OR "Selfie cámara trasera*" OR "?Selfie cámara trasera" OR "Selfiecámaratrasera" OR "?Selfiecámaratrasera" OR "Selfiecámaratrasera?" OR "#Selfiecámaratrasera"
 OR "Съемка селфи на основную камеру*" OR "?Съемка селфи на основную камеру" OR "Съемкаселфинаосновнуюкамеру" OR "?Съемкаселфинаосновнуюкамеру" OR "Съемкаселфинаосновнуюкамеру?" OR "#Съемкаселфинаосновнуюкамеру"
 OR "Selfie com câmara traseira*" OR "?Selfie com câmara traseira" OR "Selfiecomcâmaratraseira" OR "?Selfiecomcâmaratraseira" OR "Selfiecomcâmaratraseira?" OR "#Selfiecomcâmaratraseira"
 OR "후면 카메라 셀피*" OR "?후면 카메라 셀피" OR "후면카메라셀피" OR "?후면카메라셀피" OR "후면카메라셀피?" OR "#후면카메라셀피"
 OR "*メインカメラセルフィー*" OR "*メインカメラセルフィー*"
 OR "Selfie con fotocamera posteriore*" OR "?Selfie con fotocamera posteriore" OR "Selfieconfotocameraposteriore" OR "?Selfieconfotocameraposteriore" OR "Selfieconfotocameraposteriore?" OR "#Selfieconfotocameraposteriore"
 OR "HAUPTKAMERA SELFIES*" OR "?HAUPTKAMERA SELFIES" OR "HAUPTKAMERASELFIES" OR "?HAUPTKAMERASELFIES" OR "HAUPTKAMERASELFIES?" OR "#HAUPTKAMERASELFIES"
 OR "Selfie avec appareil photo arrière*" OR "?Selfie avec appareil photo arrière" OR "Selfieavecappareilphotoarrière" OR "?Selfieavecappareilphotoarrière" OR "Selfieavecappareilphotoarrière?" OR "#Selfieavecappareilphotoarrière"
 OR "Rear Cam Selfie*" OR "?Rear Cam Selfie" OR "RearCamSelfie" OR "?RearCamSelfie" OR "RearCamSelfie?" OR "#RearCamSelfie"
 OR "*后置摄像头自拍*" OR "*后置摄像头自拍*"
 OR "كاميرا السيلفي الخلفية*" OR "?كاميرا السيلفي الخلفية" OR "كاميراالسيلفيالخلفية" OR "?كاميراالسيلفيالخلفية" OR "كاميراالسيلفيالخلفية?" OR "#كاميراالسيلفيالخلفية"
 OR "Hauptkamera*" OR "?Hauptkamera" OR "Hauptkamera" OR "?Hauptkamera" OR "Hauptkamera?" OR "#Hauptkamera"
 OR "?Ảnh tự chụp" OR "Ảnh tự chụp?" OR "Ảnhtựchụp"
 OR "?Selfi" OR "Selfi?" OR "Selfi"
 OR "*自拍*" OR "*自拍*"
 OR "*เซลฟี่*" OR "*เซลฟี่*"
 OR "?СЕЛФИ" OR "СЕЛФИ?" OR "СЕЛФИ"
 OR "?Swafoto" OR "Swafoto?" OR "Swafoto"
 OR "?셀피" OR "셀피?" OR "셀피"
 OR "*セルフィー*" OR "*セルフィー*"
 OR "*自撮り*" OR "*自撮り*"
 OR "?SÉLFIE" OR "SÉLFIE?" OR "SÉLFIE"
 OR "?Selfie" OR "Selfie?" OR "Selfie"
 OR "?Selfies" OR "Selfies?" OR "Selfies"
 OR "?السيلفي" OR "السيلفي?" OR "السيلفي"
 OR "?Shooter" OR "Shooter?" OR "Shooter"
 OR "TEK TUŞLA ÇOKLU ÇEKİM*" OR "?TEK TUŞLA ÇOKLU ÇEKİM" OR "TEKTUŞLAÇOKLUÇEKİM" OR "?TEKTUŞLAÇOKLUÇEKİM" OR "TEKTUŞLAÇOKLUÇEKİM?" OR "#TEKTUŞLAÇOKLUÇEKİM"
 OR "*一鍵拍錄*" OR "*一鍵拍錄*"
 OR "*一攝多拍*" OR "*一攝多拍*"
 OR "toma única*" OR "?toma única" OR "tomaúnica" OR "?tomaúnica" OR "tomaúnica?" OR "#tomaúnica"
 OR "МУЛЬТИКАДР*" OR "?МУЛЬТИКАДР" OR "МУЛЬТИКАДР" OR "?МУЛЬТИКАДР" OR "МУЛЬТИКАДР?" OR "#МУЛЬТИКАДР"
 OR "ОДИН КАДР*" OR "?ОДИН КАДР" OR "ОДИНКАДР" OR "?ОДИНКАДР" OR "ОДИНКАДР?" OR "#ОДИНКАДР"
 OR "CAPTAÇÃO ÚNICA*" OR "?CAPTAÇÃO ÚNICA" OR "CAPTAÇÃOÚNICA" OR "?CAPTAÇÃOÚNICA" OR "CAPTAÇÃOÚNICA?" OR "#CAPTAÇÃOÚNICA"
 OR "pengambilan tunggal*" OR "?pengambilan tunggal" OR "pengambilantunggal" OR "?pengambilantunggal" OR "pengambilantunggal?" OR "#pengambilantunggal"
 OR "싱글 테이크*" OR "?싱글 테이크" OR "싱글테이크" OR "?싱글테이크" OR "싱글테이크?" OR "#싱글테이크"
 OR "*シングルテイク*" OR "*シングルテイク*"
 OR "SCATTO SINGOLO*" OR "?SCATTO SINGOLO" OR "SCATTOSINGOLO" OR "?SCATTOSINGOLO" OR "SCATTOSINGOLO?" OR "#SCATTOSINGOLO"
 OR "PRISE UNIQUE*" OR "?PRISE UNIQUE" OR "PRISEUNIQUE" OR "?PRISEUNIQUE" OR "PRISEUNIQUE?" OR "#PRISEUNIQUE"
 OR "Single Take*" OR "?Single Take" OR "SingleTake" OR "?SingleTake" OR "SingleTake?" OR "#SingleTake"
 OR "enkele opname*" OR "?enkele opname" OR "enkeleopname" OR "?enkeleopname" OR "enkeleopname?" OR "#enkeleopname"
 OR "*AI一键多拍*" OR "*AI一键多拍*"
 OR "*一键多拍*" OR "*一键多拍*"
 OR "ميزة اللقطة الواحدة*" OR "?ميزة اللقطة الواحدة" OR "ميزةاللقطةالواحدة" OR "?ميزةاللقطةالواحدة" OR "ميزةاللقطةالواحدة?" OR "#ميزةاللقطةالواحدة"
 OR "quaychậm*" OR "?quaychậm" OR "quaychậm" OR "?quaychậm" OR "quaychậm?" OR "#quaychậm"
 OR "yavaş çekim*" OR "?yavaş çekim" OR "yavaşçekim" OR "?yavaşçekim" OR "yavaşçekim?" OR "#yavaşçekim"
 OR "*慢速播放*" OR "*慢速播放*"
 OR "*慢速影片*" OR "*慢速影片*"
 OR "cámaralenta*" OR "?cámaralenta" OR "cámaralenta" OR "?cámaralenta" OR "cámaralenta?" OR "#cámaralenta"
 OR "слоу-мо*" OR "?слоу-мо" OR "слоу-мо" OR "?слоу-мо" OR "слоу-мо?" OR "#слоу-мо"
 OR "câmaralenta*" OR "?câmaralenta" OR "câmaralenta" OR "?câmaralenta" OR "câmaralenta?" OR "#câmaralenta"
 OR "슬로우 모션*" OR "?슬로우 모션" OR "슬로우모션" OR "?슬로우모션" OR "슬로우모션?" OR "#슬로우모션"
 OR "슬로 모션*" OR "?슬로 모션" OR "슬로모션" OR "?슬로모션" OR "슬로모션?" OR "#슬로모션"
 OR "슬로 모*" OR "?슬로 모" OR "슬로모" OR "?슬로모" OR "슬로모?" OR "#슬로모"
 OR "*スローモーション*" OR "*スローモーション*"
 OR "Slow Motion*" OR "?Slow Motion" OR "SlowMotion" OR "?SlowMotion" OR "SlowMotion?" OR "#SlowMotion"
 OR "Slow-Motion*" OR "?Slow-Motion" OR "Slow-Motion" OR "?Slow-Motion" OR "Slow-Motion?" OR "#Slow-Motion"
 OR "Slowmo*" OR "?Slowmo" OR "Slowmo" OR "?Slowmo" OR "Slowmo?" OR "#Slowmo"
 OR "slomo*" OR "?slomo" OR "slomo" OR "?slomo" OR "slomo?" OR "#slomo"
 OR "Slow-mo*" OR "?Slow-mo" OR "Slow-mo" OR "?Slow-mo" OR "Slow-mo?" OR "#Slow-mo"
 OR "Slo-mo*" OR "?Slo-mo" OR "Slo-mo" OR "?Slo-mo" OR "Slo-mo?" OR "#Slo-mo"
 OR "*慢速视频*" OR "*慢速视频*"
 OR "حركة بطيئة*" OR "?حركة بطيئة" OR "حركةبطيئة" OR "?حركةبطيئة" OR "حركةبطيئة?" OR "#حركةبطيئة"
 OR "수퍼슬로우모션*" OR "?수퍼슬로우모션" OR "수퍼슬로우모션" OR "?수퍼슬로우모션" OR "수퍼슬로우모션?" OR "#수퍼슬로우모션"
 OR "수퍼슬로모션*" OR "?수퍼슬로모션" OR "수퍼슬로모션" OR "?수퍼슬로모션" OR "수퍼슬로모션?" OR "#수퍼슬로모션"
 OR "SuperSlowmo*" OR "?SuperSlowmo" OR "SuperSlowmo" OR "?SuperSlowmo" OR "SuperSlowmo?" OR "#SuperSlowmo"
 OR "SuperSlow-mo*" OR "?SuperSlow-mo" OR "SuperSlow-mo" OR "?SuperSlow-mo" OR "SuperSlow-mo?" OR "#SuperSlow-mo"
 OR "Super-Slow-mo*" OR "?Super-Slow-mo" OR "Super-Slow-mo" OR "?Super-Slow-mo" OR "Super-Slow-mo?" OR "#Super-Slow-mo"
 OR "Super-Slomo*" OR "?Super-Slomo" OR "Super-Slomo" OR "?Super-Slomo" OR "Super-Slomo?" OR "#Super-Slomo"
 OR "SuperSlomo*" OR "?SuperSlomo" OR "SuperSlomo" OR "?SuperSlomo" OR "SuperSlomo?" OR "#SuperSlomo"
 OR "SuperSlo-mo*" OR "?SuperSlo-mo" OR "SuperSlo-mo" OR "?SuperSlo-mo" OR "SuperSlo-mo?" OR "#SuperSlo-mo"
 OR "THU PHÓNG CHUẨN KHÔNG GIAN*" OR "?THU PHÓNG CHUẨN KHÔNG GIAN" OR "THUPHÓNGCHUẨNKHÔNGGIAN" OR "?THUPHÓNGCHUẨNKHÔNGGIAN" OR "THUPHÓNGCHUẨNKHÔNGGIAN?" OR "#THUPHÓNGCHUẨNKHÔNGGIAN"
 OR "Uzay Yakınlaştırma*" OR "?Uzay Yakınlaştırma" OR "UzayYakınlaştırma" OR "?UzayYakınlaştırma" OR "UzayYakınlaştırma?" OR "#UzayYakınlaştırma"
 OR "*超視覺空間變焦*" OR "*超視覺空間變焦*"
 OR "*空間變焦*" OR "*空間變焦*"
 OR "*สเปซซูม*" OR "*สเปซซูม*"
 OR "Zoom Espacial*" OR "?Zoom Espacial" OR "ZoomEspacial" OR "?ZoomEspacial" OR "ZoomEspacial?" OR "#ZoomEspacial"
 OR "КРАТНИЙ КОСМІЧНИЙ ЗУМ*" OR "?КРАТНИЙ КОСМІЧНИЙ ЗУМ" OR "КРАТНИЙКОСМІЧНИЙЗУМ" OR "?КРАТНИЙКОСМІЧНИЙЗУМ" OR "КРАТНИЙКОСМІЧНИЙЗУМ?" OR "#КРАТНИЙКОСМІЧНИЙЗУМ"
 OR "ZumRuang*" OR "?ZumRuang" OR "ZumRuang" OR "?ZumRuang" OR "ZumRuang?" OR "#ZumRuang"
 OR "스페이스 줌*" OR "?스페이스 줌" OR "스페이스줌" OR "?스페이스줌" OR "스페이스줌?" OR "#스페이스줌"
 OR "*スペースズーム*" OR "*スペースズーム*"
 OR "Space Zoom*" OR "?Space Zoom" OR "SpaceZoom" OR "?SpaceZoom" OR "SpaceZoom?" OR "#SpaceZoom"
 OR "*超视觉空间变焦*" OR "*超视觉空间变焦*"
 OR "*空间变焦*" OR "*空间变焦*"
 OR "سبيسزووم*" OR "?سبيسزووم" OR "سبيسزووم" OR "?سبيسزووم" OR "سبيسزووم?" OR "#سبيسزووم"
 OR "?Thu phóng" OR "Thu phóng?" OR "Thuphóng"
 OR "?Yakınlaştırma" OR "Yakınlaştırma?" OR "Yakınlaştırma"
 OR "?變焦" OR "變焦?" OR "變焦"
 OR "?ซูม" OR "ซูม?" OR "ซูม"
 OR "?Зум" OR "Зум?" OR "Зум"
 OR "?줌" OR "줌?" OR "줌"
 OR "?ズーム" OR "ズーム?" OR "ズーム"
 OR "?Zoom" OR "Zoom?" OR "Zoom"
 OR "?Zooming" OR "Zooming?" OR "Zooming"
 OR "?Zoomed" OR "Zoomed?" OR "Zoomed"
 OR "?变焦" OR "变焦?" OR "变焦"
 OR "?缩放" OR "缩放?" OR "缩放"
 OR "?تكبير" OR "تكبير?" OR "تكبير"
 OR "chế độ Quay Phim Siêu Chống Rung *" OR "?chế độ Quay Phim Siêu Chống Rung " OR "chếđộQuayPhimSiêuChốngRung " OR "?chếđộQuayPhimSiêuChốngRung " OR "chếđộQuayPhimSiêuChốngRung ?" OR "#chếđộQuayPhimSiêuChốngRung "
 OR "Süper Dengeli Çekim*" OR "?Süper Dengeli Çekim" OR "SüperDengeliÇekim" OR "?SüperDengeliÇekim" OR "SüperDengeliÇekim?" OR "#SüperDengeliÇekim"
 OR "*超穩定動態攝影*" OR "*超穩定動態攝影*"
 OR "*極致防手震*" OR "*極致防手震*"
 OR "Суперстабілізацію*" OR "?Суперстабілізацію" OR "Суперстабілізацію" OR "?Суперстабілізацію" OR "Суперстабілізацію?" OR "#Суперстабілізацію"
 OR "SUPER ESTÁVEL*" OR "?SUPER ESTÁVEL" OR "SUPERESTÁVEL" OR "?SUPERESTÁVEL" OR "SUPERESTÁVEL?" OR "#SUPERESTÁVEL"
 OR "슈퍼 스테디*" OR "?슈퍼 스테디" OR "슈퍼스테디" OR "?슈퍼스테디" OR "슈퍼스테디?" OR "#슈퍼스테디"
 OR "*スーパー手振れ補正*" OR "*スーパー手振れ補正*"
 OR "SUPER STABILIZZATORE*" OR "?SUPER STABILIZZATORE" OR "SUPERSTABILIZZATORE" OR "?SUPERSTABILIZZATORE" OR "SUPERSTABILIZZATORE?" OR "#SUPERSTABILIZZATORE"
 OR "Superstabil*" OR "?Superstabil" OR "Superstabil" OR "?Superstabil" OR "Superstabil?" OR "#Superstabil"
 OR "ULTRA STABLE*" OR "?ULTRA STABLE" OR "ULTRASTABLE" OR "?ULTRASTABLE" OR "ULTRASTABLE?" OR "#ULTRASTABLE"
 OR "mode ultra stable*" OR "?mode ultra stable" OR "modeultrastable" OR "?modeultrastable" OR "modeultrastable?" OR "#modeultrastable"
 OR "Super Steady*" OR "?Super Steady" OR "SuperSteady" OR "?SuperSteady" OR "SuperSteady?" OR "#SuperSteady"
 OR "*超级稳定模式*" OR "*超级稳定模式*"
 OR "hızlandırılmış çekim*" OR "?hızlandırılmış çekim" OR "hızlandırılmışçekim" OR "?hızlandırılmışçekim" OR "hızlandırılmışçekim?" OR "#hızlandırılmışçekim"
 OR "*縮時攝影*" OR "*縮時攝影*"
 OR "*ไทม์แลปส์*" OR "*ไทม์แลปส์*"
 OR "таймлапс*" OR "?таймлапс" OR "таймлапс" OR "?таймлапс" OR "таймлапс?" OR "#таймлапс"
 OR "lapsodetempo*" OR "?lapsodetempo" OR "lapsodetempo" OR "?lapsodetempo" OR "lapsodetempo?" OR "#lapsodetempo"
 OR "selang masa*" OR "?selang masa" OR "selangmasa" OR "?selangmasa" OR "selangmasa?" OR "#selangmasa"
 OR "타임랩스*" OR "?타임랩스" OR "타임랩스" OR "?타임랩스" OR "타임랩스?" OR "#타임랩스"
 OR "*タイムラプス*" OR "*タイムラプス*"
 OR "Zeitraffer*" OR "?Zeitraffer" OR "Zeitraffer" OR "?Zeitraffer" OR "Zeitraffer?" OR "#Zeitraffer"
 OR "intervalle régulier*" OR "?intervalle régulier" OR "intervallerégulier" OR "?intervallerégulier" OR "intervallerégulier?" OR "#intervallerégulier"
 OR "Timelapse*" OR "?Timelapse" OR "Timelapse" OR "?Timelapse" OR "Timelapse?" OR "#Timelapse"
 OR "*间隔拍摄*" OR "*间隔拍摄*"
 OR "تداخل وقتي*" OR "?تداخل وقتي" OR "تداخلوقتي" OR "?تداخلوقتي" OR "تداخلوقتي?" OR "#تداخلوقتي"
 OR "Thời gian bay*" OR "?Thời gian bay" OR "Thờigianbay"
 OR "Uçuş Süresi*" OR "?Uçuş Süresi" OR "UçuşSüresi"
 OR "*時間軸*" OR "*時間軸*"
 OR "*การวัดระยะระหว่างเซนเซอร์กับวัตถุ*" OR "*การวัดระยะระหว่างเซนเซอร์กับวัตถุ*"
 OR "Tiempo de vuelo*" OR "?Tiempo de vuelo" OR "Tiempodevuelo"
 OR "Время пролета*" OR "?Время пролета" OR "Времяпролета"
 OR "Tempo de voo*" OR "?Tempo de voo" OR "Tempodevoo"
 OR "Masa Penerbangan*" OR "?Masa Penerbangan" OR "MasaPenerbangan"
 OR "비행시간 거리측정*" OR "?비행시간 거리측정" OR "비행시간거리측정"
 OR "Tempo di volo*" OR "?Tempo di volo" OR "Tempodivolo"
 OR "Flugzeit*" OR "?Flugzeit" OR "Flugzeit"
 OR "Temps de vol*" OR "?Temps de vol" OR "Tempsdevol"
 OR "ToF" OR "ToF"
 OR "Time of Flight*" OR "?Time of Flight" OR "TimeofFlight"
 OR "*渡越时间*" OR "*渡越时间*"
 OR "وقت التحليق*" OR "?وقت التحليق" OR "وقتالتحليق"
 OR "VDIS" OR "VDIS"
 OR "độ phân giải" OR "độphângiải"
 OR "çözünürlük" OR "çözünürlük"
 OR "*解析度*" OR "*解析度*"
 OR "ความละเอียด" OR "ความละเอียด"
 OR "resolución" OR "resolución"
 OR "разрешение" OR "разрешение"
 OR "resolução" OR "resolução"
 OR "해상도*" OR "?해상도" OR "해상도"
 OR "*解像度*" OR "*解像度*"
 OR "risoluziobe" OR "risoluziobe"
 OR "Auflösung" OR "Auflösung"
 OR "résolution" OR "résolution"
 OR "Resolution" OR "Resolution"
 OR "resolutie" OR "resolutie"
 OR "*分辨率*" OR "*分辨率*"
 OR "دقة" OR "دقة"
 OR ((8K OR 4K OR ?8K OR ?4K) NEAR/5 (影片 OR 影片?  OR วิดีโอ   OR วิดีโอ? OR  video OR video? OR #video OR  Видео OR  Видео? OR #Видео OR Відео OR Відео? OR #Відео  OR VÍDEO  OR VÍDEO? OR #VÍDEO OR  동영상 OR 동영상? OR #동영상 OR  비디오 OR 비디오? OR #비디오  OR  영상 OR 영상? OR #영상  OR ビデオ OR ビデオ? OR vidéo OR vidéo?  OR #vidéo OR 视频 OR 视频? OR #视频 OR فيديو بدقة  OR ?فيديو بدقة  OR #فيديوبدقة))

OR "Macro mode*" OR "?Macro mode" OR "Macromode" OR "?Macromode" OR "Macromode?" OR "#Macromode"
 OR "mode macro*" OR "?mode macro" OR "modemacro" OR "?modemacro" OR "modemacro?" OR "#modemacro"
 OR "*โหมดมาโคร*" OR "*โหมดมาโคร*"
 OR "접사 모드*" OR "?접사 모드" OR "접사모드" OR "?접사모드" OR "접사모드?" OR "#접사모드"
 OR "Objetivo Macro*" OR "?Objetivo Macro" OR "ObjetivoMacro" OR "?ObjetivoMacro" OR "ObjetivoMacro?" OR "#ObjetivoMacro"
 OR "Makro mod*" OR "?Makro mod" OR "Makromod" OR "?Makromod" OR "Makromod?" OR "#Makromod"
 OR "*近接撮影*"
 OR "Macro camera*" OR "?Macro camera" OR "Macrocamera" OR "?Macrocamera" OR "Macrocamera?" OR "#Macrocamera"
 OR "كاميرا ماكرو" OR "كاميراماكرو"
 OR "*微距摄像头*"
 OR "*Makro-Kamera*"
 OR "fotocamera macro" OR "fotocameramacro"
 OR "*マクロカメラ*"
 OR "*접사 카메라*" OR "*접사카메라*"
 OR "Câmara Macro" OR "CâmaraMacro"
 OR "Макро камерой" OR "Макрокамерой"
 OR "Камера для макросъёмки" OR "Камерадлямакросъёмки"
 OR "cámara macro" OR "cámaramacro"
 OR "*กล้องมาโคร*"
 OR "Makro Kamera" OR "MakroKamera"
 OR "Camera Macro" OR "CameraMacro"
 OR "Macro lens*" OR "?Macro lens" OR "Macrolens" OR "?Macrolens" OR "Macrolens?" OR "#Macrolens"
 OR "*微距镜头*"
 OR "*Objectifmacro*"
 OR "*Makro-Objektiv*"
 OR "*obiettivoMacro*"
 OR "*マクロレンズ*"
 OR "접사 렌즈" OR "접사렌즈"
 OR "lente macro" OR "lentemacro"
 OR "เลนส์ มาโคร"
 OR "微距鏡頭"
 OR "*Makro lens*" OR "*Makrolens*"
 OR "kính Macro" OR "kínhMacro"
 OR "ống kính macro" OR "ốngkínhmacro"
 OR "Fun mode*" OR "?Fun mode" OR "Funmode" OR "?Funmode" OR "Funmode?" OR "#Funmode"
 OR "Fun-Modus*" OR "?Fun-Modus" OR "Fun-Modus" OR "?Fun-Modus" OR "Fun-Modus?" OR "#Fun-Modus"
 OR "Modalità Divertimento*" OR "?Modalità Divertimento" OR "ModalitàDivertimento" OR "?ModalitàDivertimento" OR "ModalitàDivertimento?" OR "#ModalitàDivertimento"
 OR "펀(Fun) 모드" OR "펀(Fun)모드"
 OR "Modo Diversão*" OR "?Modo Diversão" OR "ModoDiversão" OR "?ModoDiversão" OR "ModoDiversão?" OR "#ModoDiversão"
 OR "Веселый режим*" OR "?Веселый режим" OR "Веселыйрежим" OR "?Веселыйрежим" OR "Веселыйрежим?" OR "#Веселыйрежим"
 OR "Modo Diversión*" OR "?Modo Diversión" OR "ModoDiversión" OR "?ModoDiversión" OR "ModoDiversión?" OR "#ModoDiversión"
 OR "eğlence modu*" OR "?eğlence modu" OR "eğlencemodu" OR "?eğlencemodu" OR "eğlencemodu?" OR "#eğlencemodu"
 OR "Chế độ thú vị*" OR "?Chế độ thú vị" OR "Chếđộthúvị" OR "?Chếđộthúvị" OR "Chếđộthúvị?" OR "#Chếđộthúvị"

OR #ExposureOnHulu


OR "Under Display Camera*" OR "?Under Display Camera" OR "UnderDisplayCamera" OR "?UnderDisplayCamera" OR "UnderDisplayCamera?" OR "#UnderDisplayCamera"
 OR "كاميرا مخفية تحت الشاشة" OR "كاميرامخفيةتحتالشاشة"
 OR "*屏下摄像头*" OR "*屏下摄像头*"
 OR "Appareil photo sous l’écran*" OR "?Appareil photo sous l’écran" OR "Appareilphotosousl’écran" OR "?Appareilphotosousl’écran" OR "Appareilphotosousl’écran?" OR "#Appareilphotosousl’écran"
 OR "Under Display-Kamera*" OR "?Under Display-Kamera" OR "UnderDisplay-Kamera" OR "?UnderDisplay-Kamera" OR "UnderDisplay-Kamera?" OR "#UnderDisplay-Kamera"
 OR "Fotocamera sotto il display*" OR "?Fotocamera sotto il display" OR "Fotocamerasottoildisplay" OR "?Fotocamerasottoildisplay" OR "Fotocamerasottoildisplay?" OR "#Fotocamerasottoildisplay"
 OR "*メインセルフィーカメラ*" OR "*メインセルフィーカメラ*"
 OR "*언더 디스플레이 카메라*" OR "*언더디스플레이카메라*"
 OR "Câmara sob o ecrã*" OR "?Câmara sob o ecrã" OR "Câmarasoboecrã" OR "?Câmarasoboecrã" OR "Câmarasoboecrã?" OR "#Câmarasoboecrã"
 OR "Подэкранная сэлфи камера*" OR "?Подэкранная сэлфи камера" OR "Подэкраннаясэлфикамера" OR "?Подэкраннаясэлфикамера" OR "Подэкраннаясэлфикамера?" OR "#Подэкраннаясэлфикамера"
 OR "Cámara debajo de la pantalla*" OR "?Cámara debajo de la pantalla" OR "Cámaradebajodelapantalla" OR "?Cámaradebajodelapantalla" OR "Cámaradebajodelapantalla?" OR "#Cámaradebajodelapantalla"
 OR "*屏下鏡頭*" OR "*屏下鏡頭*"
 OR "Ekran Altı Kamera*" OR "?Ekran Altı Kamera" OR "EkranAltıKamera" OR "?EkranAltıKamera" OR "EkranAltıKamera?" OR "#EkranAltıKamera"
 OR "Camera dưới màn hình*" OR "?Camera dưới màn hình" OR "Cameradướimànhình" OR "?Cameradướimànhình" OR "Cameradướimànhình?" OR "#Cameradướimànhình"
 OR "Cover Camera*" OR "?Cover Camera" OR "CoverCamera" OR "?CoverCamera" OR "CoverCamera?" OR "#CoverCamera"
 OR "كاميرا الغطاء" OR "كاميراالغطاء"
 OR "*外屏自拍摄像头*" OR "*外屏自拍摄像头*"
 OR "Appareil photo extérieur*" OR "?Appareil photo extérieur" OR "Appareilphotoextérieur" OR "?Appareilphotoextérieur" OR "Appareilphotoextérieur?" OR "#Appareilphotoextérieur"
 OR "Fotocamera esterna*" OR "?Fotocamera esterna" OR "Fotocameraesterna" OR "?Fotocameraesterna" OR "Fotocameraesterna?" OR "#Fotocameraesterna"
 OR "*カバーセルフィーカメラ*" OR "*カバーセルフィーカメラ*"
 OR "*커버 카메라*" OR "*커버카메라*"
 OR "Câmara do Ecrã Exterior*" OR "?Câmara do Ecrã Exterior" OR "CâmaradoEcrãExterior" OR "?CâmaradoEcrãExterior" OR "CâmaradoEcrãExterior?" OR "#CâmaradoEcrãExterior"
 OR "Сэлфи камера на внешнем экране*" OR "?Сэлфи камера на внешнем экране" OR "Сэлфикамеранавнешнемэкране" OR "?Сэлфикамеранавнешнемэкране" OR "Сэлфикамеранавнешнемэкране?" OR "#Сэлфикамеранавнешнемэкране"
 OR "Cámara externa*" OR "?Cámara externa" OR "Cámaraexterna" OR "?Cámaraexterna" OR "Cámaraexterna?" OR "#Cámaraexterna"
 OR "*กล้องที่จอนอก*" OR "*กล้องที่จอนอก*"
 OR "*機面鏡頭*" OR "*機面鏡頭*"
 OR "Kapak Kamerası*" OR "?Kapak Kamerası" OR "KapakKamerası" OR "?KapakKamerası" OR "KapakKamerası?" OR "#KapakKamerası"
 OR "Camera ngoài*" OR "?Camera ngoài" OR "Camerangoài" OR "?Camerangoài" OR "Camerangoài?" OR "#Camerangoài"
 OR "عرض اللقطة" OR "عرضاللقطة"
 OR "Grand Écran*" OR "?Grand Écran" OR "GrandÉcran" OR "?GrandÉcran" OR "GrandÉcran?" OR "#GrandÉcran"
 OR "Aufnahmenansicht*" OR "?Aufnahmenansicht" OR "Aufnahmenansicht" OR "?Aufnahmenansicht" OR "Aufnahmenansicht?" OR "#Aufnahmenansicht"
 OR "*キャプチャビュー*" OR "*キャプチャビュー*"
 OR "캡처 뷰" OR "캡처뷰"
 OR "캡쳐 뷰" OR "캡쳐뷰"
 OR "Visualização Instantâne*" OR "?Visualização Instantâne" OR "VisualizaçãoInstantâne" OR "?VisualizaçãoInstantâne" OR "VisualizaçãoInstantâne?" OR "#VisualizaçãoInstantâne"
 OR "*ПРЕДПРОСМОТР*" OR "*ПРЕДПРОСМОТР*"
 OR "Görüntü Yakalama*" OR "?Görüntü Yakalama" OR "GörüntüYakalama" OR "?GörüntüYakalama" OR "GörüntüYakalama?" OR "#GörüntüYakalama"
 OR "*Quickshot*" OR "*Quickshot*"
 OR "*ميزة Quick Shot*" OR "*ميزةQuickShot*"
 OR "*Quick Shot*" OR "*QuickShot*"
 OR "*快速拍摄*" OR "*快速拍摄*"
 OR "*Photo Express*" OR "*PhotoExpress*"
 OR "*Scatto Rapdio*" OR "*ScattoRapdio*"
 OR "*クイックショット*" OR "*クイックショット*"
 OR "*퀵 샷*" OR "*퀵샷*"
 OR "*Disparo Rápido*" OR "*DisparoRápido*"
 OR "*БЫСТРЫЙ СНИМОК*" OR "*БЫСТРЫЙСНИМОК*"
 OR "*Foto Rápida*" OR "*FotoRápida*"
 OR "*快速拍攝*" OR "*快速拍攝*"
 OR "*HIZLI ÇEKİM*" OR "*HIZLIÇEKİM*"
 OR "*CHỤP NHANH*" OR "*CHỤPNHANH*"
 OR (("Flex mode*" OR "?Flex mode" OR "Flexmode" OR "?Flexmode" OR "Flexmode?" OR "#Flexmode"
 OR "وضع Flex" OR "وضعFlex"
 OR "*立式交互模式*" OR "*立式交互模式*"
 OR "Flex-Modus*" OR "?Flex-Modus" OR "Flex-Modus" OR "?Flex-Modus" OR "Flex-Modus?" OR "#Flex-Modus"
 OR "La Modalità Flex*" OR "?La Modalità Flex" OR "LaModalitàFlex" OR "?LaModalitàFlex" OR "LaModalitàFlex?" OR "#LaModalitàFlex"
 OR "Modalità Flex*" OR "?Modalità Flex" OR "ModalitàFlex" OR "?ModalitàFlex" OR "ModalitàFlex?" OR "#ModalitàFlex"
 OR "*フレックスモード*"
 OR "*플렉스 모드*" OR "*플렉스모드*"
 OR "Режима Flex*" OR "?Режима Flex" OR "РежимаFlex" OR "?РежимаFlex" OR "РежимаFlex?" OR "#РежимаFlex"
 OR "Modo Flex*" OR "?Modo Flex" OR "ModoFlex" OR "?ModoFlex" OR "ModoFlex?" OR "#ModoFlex"
 OR "*Flex模式*" OR "*Flex模式*"
 OR "Esnek Mod*" OR "?Esnek Mod" OR "EsnekMod" OR "?EsnekMod" OR "EsnekMod?" OR "#EsnekMod"
 OR "Chế Độ Gập Mở Linh Hoạt*" OR "?Chế Độ Gập Mở Linh Hoạt" OR "ChếĐộGậpMởLinhHoạt" OR "?ChếĐộGậpMởLinhHoạt" OR "ChếĐộGậpMởLinhHoạt?" OR "#ChếĐộGậpMởLinhHoạt"
 OR "Chế độ gập mở linh hoạt Flex Mode*" OR "?Chế độ gập mở linh hoạt Flex Mode" OR "ChếđộgậpmởlinhhoạtFlexMode" OR "?ChếđộgậpmởlinhhoạtFlexMode" OR "ChếđộgậpmởlinhhoạtFlexMode?" OR "#ChếđộgậpmởlinhhoạtFlexMode") NEAR/20 (*Camera* OR *Cameras* OR "*máy ảnh*" OR *máyảnh* OR *kamerası* OR *相機* OR *ล้อง* OR *CÁMARA* OR *КАМЕРА* OR *CÂMARA* OR *카메라* OR *カメラ* OR *FOTOCAMERA* OR *KAMERA* OR *CAMÉRA* OR "*Appareil photo*" OR "*Appareilphoto*" OR *摄像头* OR الكاميرا* OR "?الكاميرا" OR "الكاميرا" OR "?الكاميرا" OR "الكاميرا?"
OR "Selfie" OR "?Selfies" OR "Selfies?" OR "Selfies" OR "?Selfi" OR "Selfi?" OR "Selfi" OR *自拍* OR *เซลฟี่* OR "?СЕЛФИ" OR "СЕЛФИ?" OR "СЕЛФИ" OR "?Swafoto" OR "Swafoto?" OR "Swafoto" OR "?셀피" OR "셀피?" OR "셀피" OR *セルフィー* OR "*自撮り*" OR "?SÉLFIE" OR "SÉLFIE?" OR "SÉLFIE" OR "?Selfie" OR "Selfie?" OR "?السيلفي" OR "السيلفي?" OR "السيلفي" ))

 OR "Автофокусировка*" OR "?Автофокусировка" OR "Автофокусировка" OR "?Автофокусировка" OR "Автофокусировка?" OR "#Автофокусировка"
 OR "*การจัดเฟรมอัตโนมัติ*" OR "*การจัดเฟรมอัตโนมัติ*"
 OR "*自動取景*" OR "*自動取景*"
 OR "Otomatik Kadrajlama*" OR "?Otomatik Kadrajlama" OR "OtomatikKadrajlama" OR "?OtomatikKadrajlama" OR "OtomatikKadrajlama?" OR "#OtomatikKadrajlama"
 OR "Tính năng Auto Framing*" OR "?Tính năng Auto Framing" OR "TínhnăngAutoFraming" OR "?TínhnăngAutoFraming" OR "TínhnăngAutoFraming?" OR "#TínhnăngAutoFraming"
 OR "ميزة Night Hyperlapse" OR "ميزةNightHyperlapse"
 OR "*夜间延时摄影*" OR "*夜间延时摄影*"
 OR "Vidéos Hyperlapse De Nuit*" OR "?Vidéos Hyperlapse De Nuit" OR "VidéosHyperlapseDeNuit" OR "?VidéosHyperlapseDeNuit" OR "VidéosHyperlapseDeNuit?" OR "#VidéosHyperlapseDeNuit"
 OR "Hyperlapse Notturno*" OR "?Hyperlapse Notturno" OR "HyperlapseNotturno" OR "?HyperlapseNotturno" OR "HyperlapseNotturno?" OR "#HyperlapseNotturno"
 OR "*ナイトハイパーラプス*" OR "*ナイトハイパーラプス*"
 OR "*야간 하이퍼랩스*" OR "*야간하이퍼랩스*"
 OR "Hiperlapso Noturno*" OR "?Hiperlapso Noturno" OR "HiperlapsoNoturno" OR "?HiperlapsoNoturno" OR "HiperlapsoNoturno?" OR "#HiperlapsoNoturno"
 OR "НОЧНАЯ СЪЕМКА В РЕЖИМЕ ГИПЕРЛАПС*" OR "?НОЧНАЯ СЪЕМКА В РЕЖИМЕ ГИПЕРЛАПС" OR "НОЧНАЯСЪЕМКАВРЕЖИМЕГИПЕРЛАПС" OR "?НОЧНАЯСЪЕМКАВРЕЖИМЕГИПЕРЛАПС" OR "НОЧНАЯСЪЕМКАВРЕЖИМЕГИПЕРЛАПС?" OR "#НОЧНАЯСЪЕМКАВРЕЖИМЕГИПЕРЛАПС"
 OR "Hyperlapse Nocturno*" OR "?Hyperlapse Nocturno" OR "HyperlapseNocturno" OR "?HyperlapseNocturno" OR "HyperlapseNocturno?" OR "#HyperlapseNocturno"
 OR "*夜間動態縮時攝影*" OR "*夜間動態縮時攝影*"
 OR "HIZLANDIRILMIŞ GECE ÇEKİMİ*" OR "?HIZLANDIRILMIŞ GECE ÇEKİMİ" OR "HIZLANDIRILMIŞGECEÇEKİMİ" OR "?HIZLANDIRILMIŞGECEÇEKİMİ" OR "HIZLANDIRILMIŞGECEÇEKİMİ?" OR "#HIZLANDIRILMIŞGECEÇEKİMİ"
 OR "CHẾ ĐỘ QUAY PHIM TRÔI NHANH*" OR "?CHẾ ĐỘ QUAY PHIM TRÔI NHANH" OR "CHẾĐỘQUAYPHIMTRÔINHANH" OR "?CHẾĐỘQUAYPHIMTRÔINHANH" OR "CHẾĐỘQUAYPHIMTRÔINHANH?" OR "#CHẾĐỘQUAYPHIMTRÔINHANH"
)

NOT ("电视"
 OR "電視" OR "電視"
 OR "ทีวี" OR "ทีวี"
 OR "تلفزيون" OR "تلفزيون"
 OR "ТВ" OR "ТВ"
 OR "TV" OR "TV"
 OR "ti vi" OR "tivi"
 OR "The Terrace*" OR "?The Terrace" OR "TheTerrace" OR "#TheTerrace"
 OR "TheTerrace*" OR "?TheTerrace" OR "TheTerrace" OR "#TheTerrace"
 OR "The Sero*" OR "?The Sero" OR "TheSero" OR "#TheSero"
 OR "TheSero*" OR "?TheSero" OR "TheSero" OR "#TheSero"
 OR "电视画境系列*" OR "?电视画境系列" OR "电视画境系列" OR "#电视画境系列"
 OR "画境系列电视*" OR "?画境系列电视" OR "画境系列电视" OR "#画境系列电视"
 OR "电视画境*" OR "?电视画境" OR "电视画境" OR "#电视画境"
 OR "画境电视*" OR "?画境电视" OR "画境电视" OR "#画境电视"
 OR "The Serif*" OR "?The Serif" OR "TheSerif" OR "#TheSerif"
 OR "TheSerif*" OR "?TheSerif" OR "TheSerif" OR "#TheSerif"
 OR "The Premiere*" OR "?The Premiere" OR "ThePremiere" OR "#ThePremiere"
 OR "ThePremiere*" OR "?ThePremiere" OR "ThePremiere" OR "#ThePremiere"
 OR "电视画壁系列*" OR "?电视画壁系列" OR "电视画壁系列" OR "#电视画壁系列"
 OR "画壁系列电视*" OR "?画壁系列电视" OR "画壁系列电视" OR "#画壁系列电视"
 OR "电视画壁*" OR "?电视画壁" OR "电视画壁" OR "#电视画壁"
 OR "画壁电视*" OR "?画壁电视" OR "画壁电视" OR "#画壁电视"
 OR "The Frame*" OR "?The Frame" OR "TheFrame" OR "#TheFrame"
 OR "TheFrame*" OR "?TheFrame" OR "TheFrame" OR "#TheFrame"
 OR "텔레비전*" OR "?텔레비전" OR "텔레비전"
 OR "โทรทัศน์*" OR "?โทรทัศน์" OR "โทรทัศน์"
 OR "تلفزيونات*" OR "?تلفزيونات" OR "تلفزيونات"
 OR "التلفاز*" OR "?التلفاز" OR "التلفاز"
 OR "テレビ*" OR "?テレビ" OR "テレビ"
 OR "телевизоров*" OR "?телевизоров" OR "телевизоров"
 OR "телевизоры*" OR "?телевизоры" OR "телевизоры"
 OR "телевидение*" OR "?телевидение" OR "телевидение"
 OR "TELEVİZYONLAR*" OR "?TELEVİZYONLAR" OR "TELEVİZYONLAR"
 OR "televisyen*" OR "?televisyen" OR "televisyen"
 OR "Televisions*" OR "?Televisions" OR "Televisions"
 OR "televisione*" OR "?televisione" OR "televisione"
 OR "televisión*" OR "?televisión" OR "televisión"
 OR "televisie*" OR "?televisie" OR "televisie"
 OR "televisiefanaat*" OR "?televisiefanaat" OR "televisiefanaat"
 OR "televisi*" OR "?televisi" OR "televisi"
 OR "Téléviseurs*" OR "?Téléviseurs" OR "Téléviseurs"
 OR "Télévisions*" OR "?Télévisions" OR "Télévisions"
 OR "TELEVISÃO*" OR "?TELEVISÃO" OR "TELEVISÃO"
 OR "máy vô tuyến truyền hình*" OR "?máy vô tuyến truyền hình" OR "máyvôtuyếntruyềnhình"
 OR "Fernsehen*" OR "?Fernsehen" OR "Fernsehen"
 OR #SamsungTV
 OR "Super Smart TV*" OR "?Super Smart TV" OR "SuperSmartTV"
 OR "QLED" OR "QLED" OR "#QLED"
 OR "?QLED" OR "QLED" OR "#QLED" OR "*QLED-TV*"
 OR "QLEDTV*" OR "?QLEDTV" OR "QLEDTV" OR "#QLEDTV"
 OR "QLED4K*" OR "?QLED4K" OR "QLED4K" OR "#QLED4K" OR "#QLED4K?"
 OR "QLED8K*" OR "?QLED8K" OR "QLED8K" OR "#QLED8K" OR "#QLED8K?"
 OR "4KQLED" OR "4KQLED" OR "#4KQLED"
 OR "8KQLED" OR "8KQLED" OR "#8KQLED"
OR #NeoQLED OR "Neo Quantum" OR NeoQLED
OR "Neo QLED 8K" OR NeoQLED8K OR "NeoQLED 8K" OR "Neo QLED8K" OR #NeoQLED8K
OR *Neo-QLED*
 OR "Mirco LED*" OR "?Mirco LED" OR "MircoLED" OR "#MircoLED"
 OR "MircoLED*" OR "?MircoLED" OR "MircoLED" OR "#MircoLED"
 OR "Crystal UHD*" OR "?Crystal UHD" OR "CrystalUHD" OR "#CrystalUHD"
 OR "CrystalUHD*" OR "?CrystalUHD" OR "CrystalUHD" OR "#CrystalUHD" OR "#CrystalUHD?"
OR "Crystal Processor 4K"
OR #samsungmicroled OR "Micro LED"
OR "4K UHD"
OR "Home cinema" OR "cine en casa?"
 OR "Add Wash*" OR "?Add Wash" OR "AddWash" OR "#AddWash"
 OR "AddWash*" OR "?AddWash" OR "AddWash" OR "#AddWash"
 OR "Odyssey*" OR "?Odyssey" OR "Odyssey" OR "#Odyssey" OR #SamsungOdyssey
 OR "AirDresser*" OR "?AirDresser" OR "AirDresser" OR "#AirDresser"
 OR "에어드레서*" OR "?에어드레서" OR "에어드레서" OR "#에어드레서"
 OR "Smart Monitor*" OR "?Smart Monitor" OR "SmartMonitor" OR "#SmartMonitor"
 OR "SmartMonitor*" OR "?SmartMonitor" OR "SmartMonitor" OR "#SmartMonitor"
 OR "Music Galaxy*" OR "?Music Galaxy" OR "MusicGalaxy" OR "#MusicGalaxy"
 OR "Samsung Service*" OR "?Samsung Service" OR "SamsungService" OR "#SamsungService"
 OR "Samsung Knox*" OR "?Samsung Knox" OR "SamsungKnox" OR "#SamsungKnox"
 OR "JetBot 90*" OR "?JetBot 90" OR "JetBot90" OR "#JetBot90"
 OR "Galaxy Book" OR "Gakaxt Book Pro" OR #GalaxyBookPro
 OR #FreshFace
 OR Frigorífico OR #SamsungFridge OR муздаткычты OR réfrigérateur OR #sidebyside
OR "No Frost"
 OR ((shooter) NEAR/5 (game OR gaming))
 OR ((resolution OR resolución) NEAR/10 (problem OR problems OR problema OR year OR year's))
OR "https://www.facebook.com/fbcameraeffects*"
OR *mp4 OR *mp3
OR #GamingWithGalaxy
OR #SamsungJet OR "Samsung Jet" OR JetStick OR "Jet Stick"
OR #DualCookFlex OR #DualCookFlex? OR "Dual Cook Flex"
OR dualcook OR dualcook? OR “dual cook” OR dual-cook
OR #TwinCoolingPlus OR #TwinCoolingPlus?
OR Twincooling OR twincooling? OR “twin cooling” OR twin-cooling
OR "Selfie stick"
OR (monitor OR monitors OR monitor? OR Monitore OR Monitore? OR #ITMonitor OR moniteurs) NEAR/5 ("*解析度*" OR "*解析度*" OR "ความละเอียด" OR "ความละเอียด" OR "resolución" OR "resolución" OR "разрешение" OR "разрешение" OR "resolução" OR "resolução" OR "해상도*" OR "?해상도" OR "해상도"  OR "*解像度*" OR "risoluziobe" OR "risoluziobe" OR "Auflösung" OR "Auflösung" OR "résolution" OR "résolution" OR "Resolution" OR "resolutie"  OR "*分辨率*" )
OR #ITMonitor OR #LedMonitor
OR *High_Resolution_Monitor* OR *HighResolutionMonitors OR *HighResMonitor* OR #GamingMonitor OR #SamsungMonitor
OR "vacuum cleaner" OR пылесос
OR #VisionaryMappingPlus
OR ((VNAND) NEAR/3 (MKX))
OR “Quantum HDR”
OR WindFree )
"""
        checker = PostChecker()
        doc = checker.replace_query(doc)
        result = self.parser.query_to_dict(doc)
        print(result)

    def test_nears_to_dict(self):
        result = self.parser.nears_to_dict(" ab OR ((a OR b) NEAR/1 (c OR d)) OR cd ")
        print(result)
